telerik/kendo-themes

- packages/default/scss/common/_forms.scss
see https://github.com/telerik/kendo-angular/issues/1305
> fix: bootstrap 4 input groups styling

- packages/default/scss/dialog/_layout.scss
- packages/default/scss/window/_layout.scss
related https://github.com/telerik/kendo/issues/8156
> fix(dialog): improve close button alignment

- packages/default/scss/gantt/_layout.scss
related https://github.com/telerik/kendo/issues/7476
> fix(spreadsheet): improve edit buttons position for rtl

- packages/default/scss/dialog/_layout.scss
related https://github.com/telerik/kendo/issues/7497
> fix(dialog): imrpove dialog buttons overflow

- packages/default/scss/upload/_layout.scss
see telerik/kendo-angular-upload#115
Moved from https://github.com/telerik/kendo-theme-default/pull/867
> chore: change upload dropzone styles

- packages/material/docs/index.md
This PR is part of the effort to enable material-theme for react.
> docs: enable react material theme-preview app

- packages/default/scss/dropdownlist/_layout.scss
- packages/material/scss/_variables.scss
- packages/material/scss/common/_forms.scss
- packages/material/scss/input/_theme.scss
- packages/material/scss/multiselect/_theme.scss
- packages/material/scss/numerictextbox/_theme.scss
https://github.com/telerik/kendo-themes/issues/43
https://github.com/telerik/kendo-themes/issues/40
https://github.com/telerik/kendo-themes/issues/44
https://github.com/telerik/kendo-themes/issues/45
> Implement Material for dropdowns

- packages/material/scss/all.scss
- packages/material/scss/splitter.scss
- packages/material/scss/splitter/_layout.scss
- packages/material/scss/splitter/_theme.scss
related https://github.com/telerik/kendo-themes/issues/47
> feat(splitter): add Material skin for Splitter

- packages/bootstrap/.npmignore
- packages/default/.npmignore
- packages/material/.npmignore
Removed a bit of redundant files, see [package contents](https://unpkg.com/@progress/kendo-theme-default@2.49.0-dev.b059e307/)
> chore: cleanup package

- packages/default/scss/grid/_theme.scss
see https://github.com/telerik/kendo-angular/issues/1354
> fix(grid): locked column data is hidden in iOS

- packages/default/scss/_variables.scss
- packages/default/scss/scrollview/_layout.scss
- packages/default/tests/fixtures/scrollview.html
- packages/material/scss/all.scss
- packages/material/scss/scrollview.scss
- packages/material/scss/scrollview/_layout.scss
- packages/material/scss/scrollview/_theme.scss
Moved from https://github.com/telerik/kendo-theme-material/pull/27
> feat: add styling for scrollview component

- CONTRIBUTING.md
A list of our commit / coding guidelines, as an attempt to fix https://github.com/telerik/kendo-theme-default/issues/578
Suggestions are welcome.
> Add coding guidelines

- packages/default/scss/window/_layout.scss
closes https://github.com/telerik/kendo-theme-default/issues/753
> fix(window): allow window to be fully maximized

- packages/bootstrap/docs/index.md
> docs: fix title

- packages/default/scss/chat/_layout.scss
Helps with the choppy scroll when using the scroll buttons.
> fix(chat): smooth scroll for card deck

- packages/default/scss/common/_forms.scss
see https://github.com/telerik/kendo-themes/issues/143
> fix(autocomplete): wrong indent in Angular RTL

- packages/material/scss/progressbar/_theme.scss
After the last change, my preprocessor (node-sass) started to break with this message:
"Functions may not be defined within control directives or other mixins"
In fact, this is invalid as we can see in the issue https://github.com/sass/sass/issues/2470.
> fix: resolve build error due to function in mixin

- packages/default/scss/common/_animations.scss
To be published together with [this PR](https://github.com/telerik/kendo-react-private/pull/309)
> fix(animations): react animation position and display properties

- packages/bootstrap/scss/combobox.scss
- packages/bootstrap/scss/multiselect.scss
- packages/default/scss/combobox.scss
- packages/default/scss/multiselect.scss
- packages/material/scss/combobox.scss
- packages/material/scss/multiselect.scss
see telerik/kendo-angular#1732
>  fix: incorrect styling when importing styles separately

- packages/material/scss/edit-form/_layout.scss
Extract and combine fixes for edit form from the following: #275 #276
> chore: improve edut form for material

- packages/default/scss/gantt/_layout.scss
- packages/default/scss/grid/_layout.scss
- packages/material/scss/all.scss
- packages/material/scss/gantt.scss
- packages/material/scss/gantt/_layout.scss
- packages/material/scss/gantt/_theme.scss
- packages/material/scss/grid/_layout.scss
- tests/visual/gantt.html
Merge after https://github.com/telerik/kendo-themes/pull/299
> feat: add Material theme for gantt

- packages/default/scss/button/_layout.scss
- packages/default/scss/tabstrip/_layout.scss
Fixes telerik/kendo-theme-bootstrap#46
> Remove focus outline

- packages/default/scss/multiselect/_layout.scss
- packages/material/scss/multiselect/_layout.scss
closes: telerik/kendo-theme-default#620
> Multiselect close button area

- packages/default/scss/gantt/_layout.scss
> fix(gantt): displaced tasks in RTL

- packages/default/scss/notification/_layout.scss
> fix(notification): notification content does not wrap on small screens

- packages/default/scss/common/_base.scss
> fix: add asp-fallback-test class for use with mvc

- packages/bootstrap/scss/scheduler/_theme.scss
- packages/default/scss/scheduler/_theme.scss
- packages/material/scss/scheduler/_theme.scss
The space between the buttons is transparent.
> fix(scheduler): adaptive view switcher background

- packages/default/scss/grid/_layout.scss
see telerik/kendo-angular#1723
> fix(grid): grid with visual scrolling not rendered properly in RTL

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/grid/_layout.scss
- packages/material/scss/_variables.scss
> non-scrollable grid command buttons margins

- packages/default/scss/button/_layout.scss
> button not displayed correctly on IE on small window sizes

- packages/default/scss/_mixins.scss
- packages/default/scss/mixins/core/_math.scss
- packages/default/scss/mixins/functions/_props.scss
Add functions to extract directional properties from values:
```scss
// signature
@function directional-property( $prop: null, $side: null, $multiplier: 1 )
// Border width uses directional-property internally
border-width("1px 0", left); // => 0
border-width("1px 0", bottom, 2); // => 2px
```
> Framework improvements

- build/publish.sh
Since command output is redirected to prevent leaking of authentication
tokens, there was no indication whether the commits have been
successfully published.
This commit adds logging so that the unsuccessful operations are
known when looking at the log. Also the build will break if the push is
not successful, in order to indicate that a manual push is required.
> chore: report bad status updates from publish.sh

- build/clean-setup.sh
Add utility script for easier setup of kendo themes repo
> chore(build): add clean setup util

- packages/default/scss/input/_layout.scss
> Grid: remove ellipsis from checkbox selection column

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/datetime/_theme.scss
- packages/default/scss/_variables.scss
- packages/default/scss/datetime/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/datetime/_layout.scss
> extract DateTime variables

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/grid/_theme.scss
- packages/default/scss/_variables.scss
- packages/default/scss/grid/_layout.scss
- packages/material/scss/_variables.scss
> Grid: sort indexes are too close to the indicator

- tests/visual/calendar.html
Rendering changed due to https://github.com/telerik/kendo-angular/issues/1840
> chore(ng): update Calendar markup

- packages/default/scss/calendar/_theme.scss
related to: https://github.com/telerik/kendo/issues/9205
> Calendar: add styles needed in the jQuery calendar

- packages/bootstrap/scss/datetime.scss
- packages/material/scss/datetime.scss
> fix(datetime): file does not list proper dependencies

- packages/default/scss/datetime/_layout.scss
- packages/default/scss/mixins/core/_math.scss
> Timepicker: minutes list is misaligned in IE and Edge

- packages/default/scss/grid/_layout.scss
related to: telerik/kendo-ui-core#4720
related PR: https://github.com/telerik/kendo/pull/9212
> Pivotgrid: pdf export cell misalignment

- packages/default/scss/pager/_layout.scss
related to https://github.com/telerik/kendo/issues/9225
> Pager: IE layout issues

- packages/bootstrap/package.json
- packages/default/package.json
- packages/material/package.json
Reverts telerik/kendo-themes#534
> Revert "chore: bump versions manually"

- packages/default/scss/common/_forms.scss
Related to: https://github.com/telerik/kendo-themes/issues/428
> Input edge specific style for inputs in flex container

- packages/bootstrap/docs/index.md
- packages/default/docs/index.md
- packages/material/docs/index.md
goes with https://github.com/telerik/kendo-angular-inputs/pull/298
> docs: add note on inputs version

- packages/default/scss/scheduler/_layout.scss
https://github.com/telerik/kendo-themes/issues/589
> fix(scheduler): cell box-sizing in IE

- packages/bootstrap/CHANGELOG.md
- packages/bootstrap/package.json
- packages/default/CHANGELOG.md
- packages/default/package.json
- packages/material/CHANGELOG.md
- packages/material/package.json
- packages/theme-tasks/CHANGELOG.md
- packages/theme-tasks/package.json
> chore(release): update changelogs

- packages/default/scss/menu/_layout.scss
related to: https://github.com/telerik/kendo-themes/issues/604
> Menu: context menu horizontal layout

- packages/bootstrap/scss/gantt/_theme.scss
- packages/default/scss/common/_base.scss
- packages/default/scss/gantt/_theme.scss
- packages/material/scss/gantt/_layout.scss
related to: https://github.com/telerik/kendo-themes/issues/314#issuecomment-462729017
> Gantt: focused toolbar items styles

- packages/default/scss/tabstrip/_layout.scss
targets https://github.com/telerik/kendo-themes/issues/353
> Tabstrip: bottom scrolling buttons on IE

- packages/default/scss/common/_icons.scss
> fix(icons): add missing icon aliases

- packages/bootstrap/docs/index.md
- packages/default/docs/index.md
- packages/material/docs/index.md
Pls let me know if the step is properly stated and if it applies to both React and Angular suites. If not, I'll have to include a conditional statement for the respective platform that's affected.
> docs: add step for including the styles

- packages/bootstrap/docs/index.md
The order is not obvious and still causes confusion, see https://github.com/telerik/kendo-angular/issues/1042
> docs: add note on order

- packages/bootstrap/scss/popup/_theme.scss
- packages/default/scss/popup/_theme.scss
> fix(dropdowns): remove list items transform transitions

- packages/default/scss/button/_layout.scss
- packages/default/scss/popup/_layout.scss
- packages/default/scss/toolbar/_layout.scss
targets: https://github.com/telerik/kendo-themes/issues/645
> Toolbar: buttons in overflow menu in IE

- packages/default/scss/grid/_layout.scss
targets: https://github.com/telerik/kendo-themes/issues/629
> Grid: column menu icon layout in IE

- packages/bootstrap/docs/index.md
- packages/default/docs/index.md
- packages/material/docs/index.md
related to https://github.com/telerik/kendo-react-private/issues/563
> docs: enhance the intro for SEO (KendoReact-related)

- package.json
Related to the following issue on Windows: https://github.com/indexzero/http-server/issues/525
> chore: set specific http server version

- packages/default/scss/drawer/_layout.scss
- packages/default/scss/drawer/_theme.scss
targets: https://github.com/telerik/kendo/issues/9715
related to: https://github.com/telerik/kendo/pull/9716
> Drawer: add scrolling styles supported in Mozilla

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/pdf-viewer/_layout.scss
- packages/material/scss/_variables.scss
> feat(pdf-viewer): add text layer sass styles

- packages/default/scss/colorpicker/_layout.scss
- packages/default/scss/drawer/_layout.scss
- packages/default/scss/input/_layout.scss
* angular drawer is not properly end aligned
* colorpicker is missing vertical align middle
* Fixes #27 -- textbox container is missing vertical align middle
> Pickers drawer fixes

- packages/default/scss/_variables.scss
- packages/default/scss/timeline/_layout.scss
- packages/material/scss/_variables.scss
- tests/visual/timeline-horizontal.html
targets: https://github.com/telerik/kendo-themes/issues/914
> Card: adjustable border radius

- packages/default/scss/input/_theme.scss
see telerik/kendo-angular#2123
> feat(inputs): autofill support for floating labels

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/combobox/_theme.scss
- packages/default/scss/_variables.scss
- packages/default/scss/combobox/_theme.scss
- packages/default/scss/toolbar/_theme.scss
- packages/material/scss/_variables.scss
related to https://github.com/telerik/kendo-themes/issues/398
> Implement independent combobox styles so they do not depend on the button styles

- packages/default/scss/radio/_theme.scss
- tests/visual/scheduler-angular-month.html
- tests/visual/scheduler-angular-rtl-month.html
ß symbol causes subsequent less compilation in the pipeline to break
> fix: remove ß from output

- packages/default/scss/_variables.scss
> Switch: off background not visible with dark swatches

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_mixins.scss
- packages/default/scss/_variables.scss
- packages/default/scss/autocomplete/_theme.scss
- packages/default/scss/button/_theme.scss
- packages/default/scss/calendar/_theme.scss
- packages/default/scss/colorpicker/_theme.scss
- packages/default/scss/combobox/_theme.scss
- packages/default/scss/datetime/_theme.scss
- packages/default/scss/dropdownlist/_theme.scss
- packages/default/scss/dropdowntree/_theme.scss
- packages/default/scss/editor/_theme.scss
- packages/default/scss/gantt/_theme.scss
- packages/default/scss/grid/_theme.scss
- packages/default/scss/input/_theme.scss
- packages/default/scss/listbox/_theme.scss
- packages/default/scss/menu/_theme.scss
- packages/default/scss/mixins/_background-clip.scss
- packages/default/scss/multiselect/_theme.scss
- packages/default/scss/numerictextbox/_theme.scss
- packages/default/scss/panelbar/_theme.scss
- packages/default/scss/pivotgrid/_theme.scss
- packages/default/scss/popup/_theme.scss
- packages/default/scss/scheduler/_theme.scss
- packages/default/scss/splitter/_theme.scss
- packages/default/scss/spreadsheet/_theme.scss
- packages/default/scss/switch/_theme.scss
- packages/default/scss/toolbar/_theme.scss
- packages/default/scss/window/_theme.scss
- packages/material/scss/_variables.scss
> feat: allow default theme reuse without background-clip

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/autocomplete/_layout.scss
- packages/default/scss/colorpicker/_layout.scss
- packages/default/scss/combobox/_layout.scss
- packages/default/scss/combobox/_theme.scss
- packages/default/scss/common/_forms.scss
- packages/default/scss/multiselect/_layout.scss
- packages/material/scss/_variables.scss
* consolidate all input variables
* move picker variables after input
* move toolbar variables after all sub-type variables
Needed for forms overhaul
> refactor: streamline variables

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/colorpicker.scss
- packages/bootstrap/scss/numerictextbox/_theme.scss
- packages/default/scss/_variables.scss
- packages/default/scss/colorpicker.scss
- packages/default/scss/common/_forms.scss
- packages/default/scss/numerictextbox/_layout.scss
- packages/default/scss/numerictextbox/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/colorpicker.scss
- packages/material/scss/common/_forms.scss
- packages/material/scss/grid/_layout.scss
- packages/material/scss/numerictextbox/_layout.scss
- packages/material/scss/numerictextbox/_theme.scss
closes: https://github.com/telerik/kendo-themes/issues/1003
> refactor(numerictextbox): extract common styles

- packages/default/scss/grid/_layout.scss
targets: https://github.com/telerik/blazor/issues/510
> Grid: add cursor pointer to filter hover in blazor

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/common/_forms.scss
- packages/bootstrap/scss/datetime/_layout.scss
- packages/bootstrap/scss/datetime/_theme.scss
- packages/default/scss/_variables.scss
- packages/default/scss/common/_forms.scss
- packages/default/scss/datetime/_layout.scss
- packages/default/scss/datetime/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/common/_forms.scss
- packages/material/scss/datetime/_layout.scss
- packages/material/scss/datetime/_theme.scss
- packages/material/scss/grid/_layout.scss
closes https://github.com/telerik/kendo-themes/issues/983
> refactor(datetime): extract common styles

- packages/default/scss/grid/_layout.scss
Required for telerik/kendo-angular-grid#870
> feat(grid): allow placing column menu inside header

- packages/default/scss/grid/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/1034
> refactor: add grid pager numerictextbox style

- .gitignore
- build/clean.sh
- build/install.sh
- package-lock.json
- packages/bootstrap/package-lock.json
- packages/default/package-lock.json
- packages/material/package-lock.json
- packages/theme-tasks/package-lock.json
Include package-lock.json for various reasons
> chore: include package-lock.json in source control

- packages/default/scss/input/_layout.scss
- packages/material/scss/common/_forms.scss
- packages/material/scss/input/_theme.scss
closes https://github.com/telerik/kendo-themes/issues/1125
Related to https://github.com/telerik/k2/issues/172
> feat(inputs): introduce k-floating-label and k-autofill classes

- packages/default/scss/chip/_layout.scss
related to https://github.com/telerik/kendo-angular-buttons/pull/313
> fix(chip): select icon position

- packages/bootstrap/.sassdocrc
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/_bootstrap-overrides.scss
- packages/bootstrap/scss/_variables.scss
- packages/default/.sassdocrc
- packages/default/docs/customization.md
- packages/default/scss/_variables.scss
- packages/default/scss/functions/_colors.scss
- packages/default/scss/input/_layout.scss
- packages/default/scss/input/_theme.scss
- packages/material/.sassdocrc
- packages/material/docs/customization.md
- packages/material/scss/_variables.scss
> reorder variables

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/tabstrip/_theme.scss
- packages/material/scss/_variables.scss
Needed for swatches based on less themes.
> fix(tabstrip): add variables for item gradient

- packages/default/scss/chat/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/1134
> fix(chat): remove visible browser outline style

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/input/_layout.scss
- packages/material/scss/_variables.scss
fixes https://github.com/telerik/kendo-themes/issues/1232
> fix(textarea): extract scss variable

- packages/bootstrap/docs/customization-buttons.md
- packages/bootstrap/docs/customization-charts.md
- packages/bootstrap/docs/customization-color-system.md
- packages/bootstrap/docs/customization-common.md
- packages/bootstrap/docs/customization-icons.md
- packages/bootstrap/docs/customization-toolbar.md
- packages/bootstrap/docs/customization-typography.md
- packages/default/docs/customization-buttons.md
- packages/default/docs/customization-charts.md
- packages/default/docs/customization-color-system.md
- packages/default/docs/customization-common.md
- packages/default/docs/customization-icons.md
- packages/default/docs/customization-toolbar.md
- packages/default/docs/customization-typography.md
- packages/material/docs/customization-buttons.md
- packages/material/docs/customization-charts.md
- packages/material/docs/customization-color-system.md
- packages/material/docs/customization-common.md
- packages/material/docs/customization-icons.md
- packages/material/docs/customization-shadows.md
- packages/material/docs/customization-tabstrip.md
- packages/material/docs/customization-toolbar.md
- packages/material/docs/customization-typography.md
- packages/theme-tasks/lib/docs/customization-variable-group.md.hbs
- packages/theme-tasks/lib/docs/sassdoc-theme.js
Generate unique slug for each sub doc page
> Fix docs generation

- packages/default/scss/adaptive/_layout.scss
- packages/default/scss/input/_layout.scss
- packages/default/scss/listgroup/_layout.scss
- tests/visual/adaptive-scheduler-edit.html
- tests/visual/grid-editing.html
Fixes https://github.com/telerik/kendo-themes/issues/785
> fix(input): update input display property

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/gantt/_theme.scss
- packages/default/scss/_variables.scss
- packages/default/scss/gantt/_layout.scss
- packages/default/scss/gantt/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/gantt/_theme.scss
part of https://github.com/telerik/kendo-themes/issues/1221
> fix(gantt): use fill mixin

- packages/bootstrap/docs/customization-color-system.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/_variables.scss
- packages/default/docs/customization-color-system.md
- packages/default/docs/customization.md
- packages/default/scss/_variables.scss
- packages/material/docs/customization-color-system.md
- packages/material/docs/customization.md
- packages/material/scss/_variables.scss
* tertiary -- a third theme color to be used alongside primary and secondary
* dark -- dark theme color
* light -- light theme color
* inverse -- depending on the luminance of the theme dark or light is light or dark
The colors by them selves do nothing. They will be used later.
> More theme colors

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/material/scss/_variables.scss
fixes: https://github.com/telerik/kendo-themes/issues/1288
> chore(chat): refactor variables

- packages/default/scss/map/_layout.scss
- packages/default/scss/map/_theme.scss
part of https://github.com/telerik/kendo-themes/issues/1221
> fix(map): use fill mixin

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/notification/_theme.scss
- packages/material/scss/_variables.scss
part of https://github.com/telerik/kendo-themes/issues/1221
> fix(notification): use fill mixin

- packages/bootstrap/docs/customization-color-system.md
- packages/bootstrap/docs/customization-component.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/_variables.scss
- packages/default/docs/customization-color-system.md
- packages/default/docs/customization-component.md
- packages/default/docs/customization.md
- packages/default/scss/_variables.scss
- packages/default/scss/common/_base.scss
- packages/default/scss/common/_loading.scss
- packages/default/scss/dataviz/_theme.scss
- packages/material/docs/customization-component.md
- packages/material/docs/customization.md
- packages/material/scss/_variables.scss
* remove usages of `$widget-` vars
* mark `$widget-` and `$accent` vars as deprecated
* regen docs.
> Remove widget var usage

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/adaptive/_layout.scss
- packages/default/scss/grid/_layout.scss
- packages/material/scss/_variables.scss
> refactor(grid): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/autocomplete/_layout.scss
- packages/material/scss/_variables.scss
> refactor(autocomplete): extract k-widget styles

- packages/bootstrap/scss/_bootstrap-overrides.scss
- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/breadcrumb/_layout.scss
- packages/default/scss/breadcrumb/_theme.scss
- packages/material/scss/_variables.scss
> refactor(breadcrumb): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/calendar/_layout.scss
- packages/default/scss/calendar/_theme.scss
- packages/material/scss/_variables.scss
> refactor(calendar): extract k-widget styles

- build/create-screenshots.sh
- build/visual-test.sh
> chore: run visual tests in parallel

- .travis.yml
* remove deprecated SUDO setting
* use OS setting
* group os, language and node_js settings
* move branches setting
> Organize travis.yml file without changing what it does

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/window/_layout.scss
- packages/default/scss/window/_theme.scss
- packages/material/scss/_variables.scss
> refactor(window): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/drawer/_layout.scss
- packages/default/scss/drawer/_theme.scss
- packages/material/scss/_variables.scss
> refactor(drawer): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/editor/_layout.scss
- packages/material/scss/_variables.scss
Part of https://github.com/telerik/kendo-themes/issues/1359
> refactor(editor): extract k-widget styles

- packages/default/scss/listview/_layout.scss
fixes: https://github.com/telerik/kendo-themes/issues/1420
> Listview: replace footer bottom border with top

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/material/scss/_variables.scss
This will be the base for the sizing system.
Needed for #1415, #1090 and #1408
> Sizing sistem base

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/all.scss
- packages/bootstrap/scss/layout/_index.scss
- packages/bootstrap/scss/layout/_layout.scss
- packages/bootstrap/scss/layout/_theme.scss
- packages/bootstrap/scss/listview/_index.scss
- packages/default/scss/_variables.scss
- packages/default/scss/all.scss
- packages/default/scss/card/_index.scss
- packages/default/scss/layout/_index.scss
- packages/default/scss/layout/_layout.scss
- packages/default/scss/listview/_index.scss
- packages/material/scss/_variables.scss
- packages/material/scss/all.scss
- packages/material/scss/card/_index.scss
- packages/material/scss/layout/_index.scss
- packages/material/scss/layout/_layout.scss
- packages/material/scss/layout/_theme.scss
- packages/material/scss/listview/_index.scss
- packages/theme-tasks/lib/docs/sassdoc-theme.js
Utility class names. To be used from kendo-jquery-listview
> Layout styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/listbox/_layout.scss
- packages/material/scss/_variables.scss
> refactor(listbox): extract k-widget styles

- packages/default/scss/popup/_theme.scss
- packages/material/scss/common/material/_palettes.scss
- packages/material/scss/menu/_theme.scss
> fix: remove traling commas in maps and params list no to break the build

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/pager/_layout.scss
- packages/default/scss/pager/_theme.scss
- packages/material/scss/_variables.scss
> refactor(pager): extract k-widget styles

- packages/default/scss/numerictextbox/_layout.scss
- packages/default/scss/numerictextbox/_theme.scss
> refactor(numerictextbox): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/panelbar/_layout.scss
- packages/default/scss/panelbar/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/panelbar/_theme.scss
> refactor(panelbar): extract k-widget styles

- packages/default/docs/customization-buttons.md
- packages/default/docs/customization-color-system.md
- packages/default/docs/customization-common.md
- packages/default/docs/customization.md
- packages/theme-tasks/docs/templates/includes/theme-variables-row.md.njk
This PR fixes the following issue:
https://www.telerik.com/kendo-angular-ui/components/styling/theme-default/customization-color-system/
(check "Computed value" of the "$primary" var)
> update docs resolvedValue color template

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/pdf-viewer/_layout.scss
- packages/default/scss/pdf-viewer/_theme.scss
- packages/material/scss/_variables.scss
> refactor(pdf-viewer): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/progressbar/_layout.scss
- packages/default/scss/progressbar/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/progressbar/_theme.scss
> refactor(progressbar): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/slider/_layout.scss
- packages/material/scss/_variables.scss
> refactor(slider): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/spreadsheet/_theme.scss
- packages/default/scss/_variables.scss
- packages/default/scss/spreadsheet/_layout.scss
- packages/default/scss/spreadsheet/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/spreadsheet/_theme.scss
> refactor(spreadsheet): extract k-widget styles

- packages/default/scss/stepper/_layout.scss
> refactor(stepper): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/switch/_layout.scss
- packages/material/scss/_variables.scss
> refactor(switch): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/tabstrip/_layout.scss
- packages/material/scss/_variables.scss
> refactor(tabstrip): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/tooltip/_layout.scss
- packages/material/scss/_variables.scss
> refactor(tooltip): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/toolbar/_layout.scss
- packages/material/scss/_variables.scss
> refactor(toolbar): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/treeview/_layout.scss
- packages/material/scss/_variables.scss
> refactor(treeview): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/upload/_layout.scss
- packages/material/scss/_variables.scss
> refactor(upload): extract k-widget styles

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/checkbox/_layout.scss
- packages/default/scss/forms/_layout.scss
- packages/default/scss/forms/_theme.scss
- packages/material/scss/_variables.scss
- tests/visual/form-field-dateinputs.html
- tests/visual/form-field-dropdowns.html
- tests/visual/form-field-fieldset.html
- tests/visual/form-field-inputs-rtl.html
- tests/visual/form-field-inputs.html
> fix(forms): various fixes and adjustments

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/layout/_layout.scss
- packages/default/scss/listview/_layout.scss
- packages/material/scss/_variables.scss
Styles for listview features like item item padding square or borders etc.
Needed for jquery listview
> Listview fixes

- packages/default/scss/common/_utils.scss
- packages/default/scss/common/utils/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/1439
> feat(utils): add layout utility classes

- packages/default/scss/toolbar/_layout.scss
- packages/default/scss/upload/_layout.scss
> fix(toolbar): add styles for toolbar template containers

- packages/default/scss/multiselect/_layout.scss
- packages/default/scss/popup/_layout.scss
Fixes https://github.com/telerik/kendo-themes/issues/1569
> fix(combobox): broken layout when virtual scrolling is enabled

- packages/default/scss/calendar/_theme.scss
fixes: https://github.com/telerik/blazor/issues/853
> calendar: add style on hover state

- gulpfile.js
- package-lock.json
- package.json
* to be used for the documentation
* since sass-variables-parser is unmaintained, there is some trickery applied to bootstrap files
> chore: add funcitonality to resolve variables values

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/gantt/_theme.scss
- packages/default/scss/_variables.scss
- packages/default/scss/dataviz/_theme.scss
- packages/default/scss/gantt/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/gantt/_theme.scss
> Add missing border colors

- packages/default/scss/scheduler/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/1150
> fix(scheduler): missing border

- packages/material/scss/_variables.scss
- packages/material/scss/common/material/_themeing.scss
> fix(progressbar): use material-color instead of material-contrast to resolve correct values

- lerna.json
- package-lock.json
- package.json
- packages/bootstrap/package-lock.json
- packages/default/package-lock.json
- packages/material/package-lock.json
- packages/theme-tasks/package-lock.json
Update lerna to v3 along with related dependencies.
> chore: update lerna to v3

- .commitlintrc.json
- build/publish.sh
* use --dist-tag instead of --npm-tag
* add infra keyword for commits
> infra(lerna): checkout develop before publishing dev relase

- packages/bootstrap/scss/wizard/_index.scss
- packages/default/scss/wizard/_index.scss
- packages/material/scss/wizard/_index.scss
related to: https://github.com/telerik/kendo/issues/11018
> fix(wizard): add button, stepper and form as wizard dependencies

- packages/default/scss/scheduler/_layout.scss
The fix should bring the final RecurrenceEditor design in the Kendo jQuery suites:
https://github.com/telerik/kendo-ux/blob/master/themes/default/PNG/component-dialogs.png
> chore(scheduler): adjust RecEd numerics and ddls widths telerik/kendo#11112

- packages/nouvelle/build/embed-dependencies
- packages/nouvelle/docs/customization-typography.md
- packages/nouvelle/docs/customization.md
- packages/nouvelle/scss/_variables.scss
- packages/nouvelle/scss/button/_layout.scss
- packages/nouvelle/scss/button/_variables.scss
minor change to trigger new version release
> Add embed deps

- packages/bootstrap/scss/all.scss
- packages/bootstrap/scss/card/_index.scss
- packages/bootstrap/scss/typography/_index.scss
- packages/bootstrap/scss/typography/_layout.scss
- packages/default/scss/all.scss
- packages/default/scss/card/_index.scss
- packages/default/scss/styling/_index.scss
- packages/default/scss/typography/_index.scss
- packages/default/scss/typography/_layout.scss
- packages/material/scss/all.scss
- packages/material/scss/card/_index.scss
- packages/material/scss/typography/_index.scss
- packages/material/scss/typography/_layout.scss
> refactor(common): expose typography into separate module

- build/clean.sh
- build/install.sh
- package-lock.json
- package.json
- packages/theme-tasks/gulpfile.js
* compatibility with node < 10
* fork logic for travis and local development
> compatibility with node < 10

- packages/bootstrap/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/button/_layout.scss
- packages/default/scss/button/_theme.scss
- packages/material/scss/_variables.scss
- packages/material/scss/button/_layout.scss
> refactor(buttons): extract k-widget styles

- packages/default/scss/chip/_layout.scss
> fix(chip): broken layout in IE11

- packages/default/scss/treelist/_layout.scss
part of: https://github.com/telerik/kendo/issues/11209
> TreeList change drop-hint translate

- gulpfile.js
- packages/bootstrap/scss/swatches/bootstrap-3.scss
- packages/classic/scss/swatches/_classic.scss
use bootstrap 3 based colors.
Part of #994
> Add bootstrap 3 compatible swatch

- packages/default/scss/gantt/_layout.scss
- tests/visual/gantt.html
@silviyaboteva I am not sure how responsive toolbar is handled in react, but if we need to, we can additionally extend the styles.
> Gantt toolbar

- .browserslistrc
- gulpfile.js
> use .browserlistrc file instead of inline variables

- packages/default/scss/calendar/_layout.scss
> fix(calendar): center content of infinite calendar when width is wider

- packages/bootstrap/scss/_variables.scss
- packages/classic/scss/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/checkbox/_theme.scss
- packages/default/scss/radio/_theme.scss
- packages/material/scss/_variables.scss
> Radio checkbox invalid

- packages/bootstrap/scss/swatches/bootstrap-3-dark.scss
- packages/bootstrap/scss/swatches/bootstrap-3.scss
> add dark bootstrap-3 based swatch

- packages/bootstrap/scss/grid/_theme.scss
- packages/default/scss/grid/_layout.scss
- packages/default/scss/grid/_theme.scss
- packages/material/scss/grid/_theme.scss
> Blazor fixes

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/drawer/_index.scss
- packages/bootstrap/scss/drawer/_variables.scss
- packages/classic/scss/_variables.scss
- packages/classic/scss/drawer/_index.scss
- packages/classic/scss/drawer/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/drawer/_index.scss
- packages/default/scss/drawer/_variables.scss
- packages/material/scss/_variables.scss
- packages/material/scss/drawer/_index.scss
- packages/material/scss/drawer/_variables.scss
Part of #1872
Notable changes:
* rename selected-hover-color variable to selected-hover-text
> Extract drawer variables into separate files

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/editor/_index.scss
- packages/bootstrap/scss/editor/_variables.scss
- packages/classic/scss/_variables.scss
- packages/classic/scss/editor/_index.scss
- packages/classic/scss/editor/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/editor/_index.scss
- packages/default/scss/editor/_variables.scss
- packages/material/scss/_variables.scss
- packages/material/scss/editor/_index.scss
- packages/material/scss/editor/_variables.scss
> Extract editor variables into separate files

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/filter/_index.scss
- packages/bootstrap/scss/filter/_variables.scss
- packages/classic/scss/_variables.scss
- packages/classic/scss/filter/_index.scss
- packages/classic/scss/filter/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/filter/_index.scss
- packages/default/scss/filter/_variables.scss
- packages/material/scss/_variables.scss
- packages/material/scss/filter/_index.scss
- packages/material/scss/filter/_variables.scss
> Extract filter variables into separate files

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/checkbox/_index.scss
- packages/bootstrap/scss/checkbox/_variables.scss
- packages/bootstrap/scss/radio/_index.scss
- packages/bootstrap/scss/radio/_variables.scss
- packages/bootstrap/scss/treeview/_index.scss
- packages/bootstrap/scss/treeview/_variables.scss
- packages/classic/scss/_variables.scss
- packages/classic/scss/checkbox/_index.scss
- packages/classic/scss/checkbox/_variables.scss
- packages/classic/scss/radio/_index.scss
- packages/classic/scss/radio/_variables.scss
- packages/classic/scss/treeview/_index.scss
- packages/classic/scss/treeview/_variables.scss
- packages/default/scss/_variables.scss
- packages/default/scss/checkbox/_index.scss
- packages/default/scss/checkbox/_variables.scss
- packages/default/scss/radio/_index.scss
- packages/default/scss/radio/_variables.scss
- packages/default/scss/treeview/_index.scss
- packages/default/scss/treeview/_variables.scss
- packages/material/scss/_variables.scss
- packages/material/scss/checkbox/_index.scss
- packages/material/scss/checkbox/_variables.scss
- packages/material/scss/radio/_index.scss
- packages/material/scss/radio/_variables.scss
- packages/material/scss/treeview/_index.scss
- packages/material/scss/treeview/_variables.scss
Part of #1872
Note: both treeview and radio depend on checkbox, so I can't extract checkbox without extracting them first.
> Extract treeview, checkbox and radio button variables

- packages/bootstrap/scss/checkbox/_variables.scss
- packages/classic/scss/checkbox/_variables.scss
- packages/default/scss/checkbox/_variables.scss
- packages/material/scss/checkbox/_variables.scss
Same as #1914 but for checkbox
> fix(checkbox): use calc to calculate checkbox line height

- docs/templates/customization.md.njk
- package.json
- packages/bootstrap/docs/customization.md
- packages/classic/docs/customization.md
- packages/default/docs/customization.md
- packages/material/docs/customization.md
- packages/nouvelle/docs/customization.md
Extract parts of #1816 to reduce complexity.
> Pre katana v2

- packages/default/scss/calendar/_layout.scss
- packages/default/scss/calendar/_theme.scss
- packages/material/scss/calendar/_layout.scss
related to https://github.com/telerik/kendo-themes/issues/876
> refactor(calendar): scope k-content and k-title

- .github/workflows/ci_nightly.yml
Add nightly ci github action:
* runs mon - fri at midnight
* lints
* builds themes
> Add nightly ci github action

- packages/default/scss/calendar/_layout.scss
- packages/default/scss/calendar/_theme.scss
- packages/material/scss/calendar/_layout.scss
related to https://github.com/telerik/kendo-themes/issues/1278
> refactor(calendar): add class selectors for table elements

- .github/workflows/ci_nightly.yml
- .github/workflows/release_dev.yml
- .github/workflows/release_stable.yml
- packages/bootstrap/scss/colorpicker/_index.scss
- packages/classic/scss/colorpicker/_index.scss
- packages/default/scss/colorpicker/_index.scss
- packages/default/scss/common/_animations.scss
- packages/material/scss/colorpicker/_index.scss
* remove duplicate animation
* require utils/flex in color picker
* streamline release actions
> Various fixes

- package.json
- scripts/new-component/create-component-files.js
- scripts/new-component/templates/_index.scss.njk
- scripts/new-component/templates/_layout.scss.njk
- scripts/new-component/templates/_theme.scss.njk
- scripts/new-component/templates/_variables.scss.njk
- scripts/utils.js
closes: https://github.com/telerik/kendo-themes/issues/2016
After this PR is merged, I will create a Wiki - "Steps of creating a new component"
> script for creating initial files for new components

- packages/bootstrap/scss/all.scss
- packages/bootstrap/scss/fab/_index.scss
- packages/bootstrap/scss/fab/_layout.scss
- packages/bootstrap/scss/fab/_theme.scss
- packages/bootstrap/scss/fab/_variables.scss
- packages/classic/scss/all.scss
- packages/classic/scss/fab/_index.scss
- packages/classic/scss/fab/_layout.scss
- packages/classic/scss/fab/_theme.scss
- packages/classic/scss/fab/_variables.scss
- packages/default/scss/all.scss
- packages/default/scss/fab/_index.scss
- packages/default/scss/fab/_layout.scss
- packages/default/scss/fab/_theme.scss
- packages/default/scss/fab/_variables.scss
- packages/default/scss/utils/_position.scss
- packages/material/scss/all.scss
- packages/material/scss/fab/_index.scss
- packages/material/scss/fab/_layout.scss
- packages/material/scss/fab/_theme.scss
- packages/material/scss/fab/_variables.scss
- tests/visual/fab-items.html
- tests/visual/fab-positions-angular.html
- tests/visual/fab-positions.html
- tests/visual/fab-rtl.html
- tests/visual/fab-shape-size.html
- tests/visual/fab-states.html
- tests/visual/fab.html
Part of: https://github.com/telerik/kendo-themes/issues/1948
> Fab styles

- packages/bootstrap/scss/fab/_theme.scss
- packages/default/scss/fab/_layout.scss
- packages/default/scss/fab/_theme.scss
- packages/material/scss/fab/_theme.scss
- tests/visual/fab-items.html
* duplicate selectors for kendo-angular button service
* remove explicit positioning from fab popup
* flip item label an icon in rtl
> Fab improvements

- packages/default/scss/input/_layout.scss
> Input: styled input with icon on left/right

- packages/default/scss/mixins/_hide-scrollbar.scss
> fix(calendar): generated css has duplicate code

- packages/bootstrap/scss/utils/_index.scss
- packages/bootstrap/scss/utils/_spacer.scss
- packages/classic/scss/utils/_index.scss
- packages/classic/scss/utils/_spacer.scss
- packages/default/scss/utils/_index.scss
- packages/default/scss/utils/_spacer.scss
- packages/material/scss/utils/_index.scss
- packages/material/scss/utils/_spacer.scss
I am adding this class / style so we could avoid repetition of styles in different components.
> fix: add generic spacer styles

- packages/bootstrap/scss/fab/_variables.scss
- packages/classic/scss/fab/_variables.scss
- packages/default/scss/fab/_layout.scss
- packages/default/scss/fab/_variables.scss
- packages/material/scss/fab/_variables.scss
Circle / square fabs should not grow horizontally in size
/cc @silviyaboteva @Juveniel @elena-gancheva @Raisolution
> Constrain circle and square shapes in size

- packages/bootstrap/scss/_variables.scss
- packages/bootstrap/scss/utils/_index.scss
- packages/bootstrap/scss/utils/_pointer-events.scss
- packages/bootstrap/scss/utils/_touch-action.scss
- packages/bootstrap/scss/utils/_user-select.scss
- packages/classic/scss/_variables.scss
- packages/classic/scss/utils/_index.scss
- packages/classic/scss/utils/_pointer-events.scss
- packages/classic/scss/utils/_touch-action.scss
- packages/classic/scss/utils/_user-select.scss
- packages/default/scss/_variables.scss
- packages/default/scss/slider/_layout.scss
- packages/default/scss/utils/_float.scss
- packages/default/scss/utils/_index.scss
- packages/default/scss/utils/_overflow.scss
- packages/default/scss/utils/_pointer-events.scss
- packages/default/scss/utils/_spacing.scss
- packages/default/scss/utils/_touch-action.scss
- packages/default/scss/utils/_user-select.scss
- packages/material/scss/_variables.scss
- packages/material/scss/utils/_index.scss
- packages/material/scss/utils/_pointer-events.scss
- packages/material/scss/utils/_touch-action.scss
- packages/material/scss/utils/_user-select.scss
- tests/visual/adaptive-grid-columnmenu.html
Add utility classes for:
* overflow
* horizontal and vertical padding and margin
* clear / float
* pointer events / touch action / user select
A tiny refactoring in slider
Fixes: #2065. Fixes: #2105.
> Extend utilities

- packages/default/scss/filemanager/_layout.scss
> Filemanager treeview scroll

- packages/default/scss/window/_layout.scss
> Make textbox / textarea inside prompt 100% wide

- packages/bootstrap/scss/utils/_index.scss
- packages/bootstrap/scss/utils/_order.scss
- packages/classic/scss/utils/_index.scss
- packages/classic/scss/utils/_order.scss
- packages/default/scss/utils/_index.scss
- packages/default/scss/utils/_order.scss
- packages/material/scss/utils/_index.scss
- packages/material/scss/utils/_order.scss
> Add utility classes for order

- packages/default/scss/spreadsheet/_layout.scss
> Мove last cell editor button infront of the cell so it's clickable

- packages/bootstrap/scss/stepper/_index.scss
- packages/classic/scss/stepper/_index.scss
- packages/default/scss/stepper/_index.scss
- packages/material/scss/stepper/_index.scss
Stepper uses progressbar element but does not include the progressbar styling.
> fix(stepper): Stepper is missing progressbar styling 

- packages/default/scss/floating-label/_theme.scss
Reported by customer
TID: 1504251
> Traling comma breaks build with WebCompiler VS addon

- packages/default/scss/tabstrip/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/2268
> fix(tabstrip): remove at-root rule

- packages/default/scss/utils/_aria.scss
- packages/default/scss/utils/_display.scss
- packages/default/scss/utils/_float.scss
- packages/default/scss/utils/_order.scss
- packages/default/scss/utils/_overflow.scss
- packages/default/scss/utils/_pointer-events.scss
- packages/default/scss/utils/_position.scss
- packages/default/scss/utils/_spacer.scss
- packages/default/scss/utils/_spacing.scss
- packages/default/scss/utils/_table-layout.scss
- packages/default/scss/utils/_text.scss
- packages/default/scss/utils/_touch-action.scss
- packages/default/scss/utils/_transform.scss
- packages/default/scss/utils/_user-select.scss
needs: https://github.com/telerik/kendo-themes/pull/2189
> docs: add content on util classes

- packages/default/scss/dataviz/_layout.scss
> Remove unused k-border class

- package-lock.json
- package.json
Husky 5.0.9 has some issues with hooks. See https://github.com/typicode/husky/issues/872
> Revert to husky 4.3.8

- tests/visual/expansion-panel-rtl.html
- tests/visual/expansion-panel.html
> Don't use display grid for expander pages

- packages/default/scss/drawer/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/2367
> fix(drawer): increase overlay selector specificity

- packages/default/scss/checkbox/_layout.scss
- packages/default/scss/checkbox/_theme.scss
https://github.com/telerik/kendo-themes/issues/2376
> feat: add interaction states for checkboxes

- packages/default/scss/radio/_layout.scss
- packages/default/scss/radio/_theme.scss
https://github.com/telerik/kendo-themes/issues/2376
> feat: add interaction states for radio buttons

- packages/default/scss/treeview/_layout.scss
targets telerik/kendo-ui-core#6321
> Focus should be on root and not on wrapper

- packages/default/scss/popup/_layout.scss
Revert fc04994912fe50752817f78316981704b234c201
> Revert fix for virtual scrolling container

- packages/default/scss/action-sheet/_theme.scss
- packages/default/scss/panelbar/_theme.scss
- packages/default/scss/utils/_border.scss
fixes telerik/kendo-themes#2480
> fix: traling commas break builds

- packages/bootstrap/docs/customization-charts.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/grid/_theme.scss
- packages/default/scss/grid/_theme.scss
- packages/material/docs/customization-charts.md
- packages/material/docs/customization.md
- packages/material/scss/grid/_theme.scss
- tests/visual/src/misc/grid-pager.html
fixes https://github.com/telerik/kendo-themes/issues/2500
> fix(grid): add pager focus styles

- packages/bootstrap/scss/core/_extra.scss
- packages/bootstrap/scss/core/_index.scss
- packages/bootstrap/scss/utils/_aria.scss
- packages/bootstrap/scss/utils/_index.scss
- packages/classic/scss/core/_extra.scss
- packages/classic/scss/core/_index.scss
- packages/classic/scss/utils/_aria.scss
- packages/classic/scss/utils/_index.scss
- packages/default/scss/core/_extra.scss
- packages/default/scss/core/_index.scss
- packages/default/scss/core/_normalize.scss
- packages/default/scss/utils/_index.scss
- packages/material/scss/core/_extra.scss
- packages/material/scss/core/_index.scss
- packages/material/scss/utils/_aria.scss
- packages/material/scss/utils/_index.scss
- packages/nouvelle/scss/core/_extra.scss
- packages/nouvelle/scss/core/_normalize.scss
- packages/nouvelle/scss/core/index.scss
Created `_extra.scss` file in the core module and moved the `.k-sr-only` class there.
> feat(core): add extra scss file

- packages/material/docs/customization-color-system.md
- packages/material/docs/customization.md
- packages/material/lib/themebuilder/smoke.json
- packages/material/scss/_variables.scss
- packages/material/scss/core/_color-system.scss
- packages/material/scss/swatches/pink-bluegrey-dark.scss
- packages/material/scss/tooltip/_variables.scss
- tests/visual/src/misc/form-field-dateinputs-angular.html
- tests/visual/src/misc/form-field-dateinputs-react.html
- tests/visual/src/misc/form-field-dropdowns-angular.html
- tests/visual/src/misc/form-field-dropdowns-react.html
- tests/visual/src/misc/form-field-fieldset-angular.html
- tests/visual/src/misc/form-field-fieldset-react.html
- tests/visual/src/misc/form-field-inputs-angular-rtl.html
- tests/visual/src/misc/form-field-inputs-angular.html
- tests/visual/src/misc/form-field-inputs-react.html
- tests/visual/src/misc/form-misc-angular.html
- tests/visual/src/misc/form-misc-react.html
Needed for Material theme and themebuilder
> Switch to american english spelling for grey

- .github/workflows/release_dev.yml
- .github/workflows/release_stable.yml
- gulpfile.js
- package.json
> Ship sass swatches source files in dist

- packages/default/scss/calendar/_layout.scss
> Reduce selector specificity where possible

- packages/default/scss/icons/_layout.scss
> Keep font-face styles at root so nesthet themes will work

- packages/bootstrap/scss/upload/_variables.scss
- packages/classic/scss/upload/_variables.scss
- packages/default/scss/upload/_variables.scss
- packages/material/scss/upload/_variables.scss
> Use spacing map to size upload items

- packages/bootstrap/scss/scheduler/_variables.scss
- packages/classic/scss/scheduler/_variables.scss
- packages/default/scss/scheduler/_layout.scss
- packages/default/scss/scheduler/_variables.scss
- packages/material/scss/scheduler/_variables.scss
> Introduce variables for scheduler cell padding

- packages/default/scss/toolbar/_layout.scss
Needed for angular scheduler where exact toolbar rendering is not quite possible.
> Add styles for toolbar group

- packages/default/scss/scheduler/_layout.scss
> Use scheduler-cell-padding variable for all cells

- packages/bootstrap/scss/_bootstrap-overrides.scss
- packages/bootstrap/scss/overlay/_variables.scss
- packages/bootstrap/scss/window/_variables.scss
> Unlink window variables

- packages/bootstrap/scss/_bootstrap-overrides.scss
> fix(input): reduce direct referencing of bootstrap variables

- packages/bootstrap/docs/customization-component.md
- packages/bootstrap/docs/customization-grid.md
- packages/bootstrap/docs/customization-tabstrip.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/_bootstrap-overrides.scss
- packages/bootstrap/scss/_variables.scss
> Unlink root variables

- packages/default/scss/toolbar/_theme.scss
> Do not override focsed state of disabled flat buttons

- packages/default/scss/spreadsheet/_layout.scss
- packages/material/scss/spreadsheet/_layout.scss
Part of #2551.
Fixes telerik/kendo#12923
> Do not extend flat buttons in spreadsheet

- .github/workflows/publish_swatches.yml
> chore: fix CDN publish workflow

- packages/default/scss/calendar/_layout.scss
> Infinite calendar does not scroll as it should

- .github/workflows/merge_develop.yml
> Use token for merge master workflow

- packages/bootstrap/scss/appbar/_variables.scss
- packages/classic/scss/appbar/_variables.scss
- packages/default/scss/appbar/_layout.scss
- packages/default/scss/appbar/_variables.scss
- packages/material/scss/appbar/_variables.scss
> Use higher zindex for sticky appbar

- packages/material/scss/chat/_variables.scss
> Message box uses white background in dark themes

- packages/bootstrap/scss/datetime/_variables.scss
- packages/classic/scss/datetime/_variables.scss
- packages/default/scss/datetime/_variables.scss
- packages/material/scss/datetime/_variables.scss
> Increase minimum popup width

- packages/default/scss/tilelayout/_layout.scss
> Items should have lower z-index by default

- packages/default/scss/scrollview/_layout.scss
Resolves https://github.com/telerik/kendo-themes/issues/2742
> fix(scrollview): fix syntax error on application build

- packages/default/scss/tooltip/_layout.scss
> Switch from display inline-flex to flex to remove extra space

- packages/default/scss/scheduler/_layout.scss
> Scheduler resource cells should not flex

- packages/bootstrap/scss/_bootstrap-overrides.scss
> use conditional colors for tooltip in bootstrap dark swatches

- packages/bootstrap/docs/index.md
Resolves: https://github.com/telerik/kendo-themes/issues/2730
//cc @nrch
> docs(bootstrap): add statement about Bootstrap v5 support

- packages/default/scss/pivotgrid/_layout.scss
- packages/default/scss/spreadsheet/_layout.scss
Fixes: https://github.com/telerik/kendo-themes/issues/2811
> Align items warning

- packages/bootstrap/scss/captcha/_index.scss
- packages/bootstrap/scss/orgchart/_index.scss
- packages/classic/scss/captcha/_index.scss
- packages/classic/scss/orgchart/_index.scss
- packages/default/scss/captcha/_index.scss
- packages/default/scss/orgchart/_index.scss
- packages/material/scss/captcha/_index.scss
- packages/material/scss/orgchart/_index.scss
fixes: https://github.com/telerik/kendo-themes/issues/2785
> fix: import missing dependencies for orgchart and captcha

- docs/components/avatar/index.md
- docs/components/button/index.md
- docs/components/checkbox/index.md
- docs/components/radio/index.md
- docs/components/switch/index.md
- packages/default/scss/button/index.md
Transfer docs from v5 branch for easier rebasing / merging
> Transfer docs

- packages/default/scss/colorgradient/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/2959
> feat(colorgradient): add color contrast svg styles

- docs/components/dropdowngrid/index.md
@joneff please cherry-pick this in develop also, so that the Katana Themes build can pass successfully ...
> chore(docs): update dropdowngrid docs

- packages/default/scss/filter/_layout.scss
- packages/default/scss/filter/_theme.scss
fixes https://github.com/telerik/kendo-themes/issues/2790
> Adjust styles for angular rendering

- packages/default/scss/switch/_layout.scss
> chore(switch): extend rtl selectors

- packages/bootstrap/scss/panelbar/_variables.scss
- packages/classic/scss/panelbar/_variables.scss
- packages/default/scss/panelbar/_theme.scss
- packages/default/scss/panelbar/_variables.scss
- packages/material/scss/panelbar/_variables.scss
> Add variables to allow customization when expanding panelbar

- packages/default/scss/forms/_layout.scss
> Remove unexpected margin before a form field preceded by hidden field

- packages/html/src/list/README.md
targets: https://github.com/telerik/kendo-themes/issues/3090
> chore(list): update readme with filter and no-data rendering

- packages/default/scss/treeview/_layout.scss
targets: https://github.com/telerik/kendo-themes/issues/3110
> Fix treeview group reset

- packages/default/scss/checkbox/_theme.scss
- packages/default/scss/input/_theme.scss
related to: https://github.com/telerik/kendo-themes/issues/3050
> fix: remove :invalid selector from themes

- packages/default/scss/slider/_layout.scss
needed for kendo-angular-slider (and range slider)
> Tweak slider so it works with extra slider-wrap element

- packages/default/scss/menu/_theme.scss
Fixes: https://github.com/telerik/kendo-themes/issues/3223
> Menu item focus v5

- packages/default/scss/panelbar/_layout.scss
fixes: https://github.com/telerik/kendo-themes/issues/3254
> fix(panelbar): scope content styles

- packages/bootstrap/lib/swatches/bootstrap-3-dark.json
- packages/bootstrap/lib/swatches/bootstrap-3.json
- packages/bootstrap/lib/swatches/bootstrap-4-dark.json
- packages/bootstrap/lib/swatches/bootstrap-4.json
- packages/bootstrap/lib/swatches/bootstrap-main-dark.json
- packages/bootstrap/lib/swatches/bootstrap-main.json
- packages/bootstrap/lib/swatches/bootstrap-nordic.json
- packages/bootstrap/lib/swatches/bootstrap-turquoise-dark.json
- packages/bootstrap/lib/swatches/bootstrap-turquoise.json
- packages/bootstrap/lib/swatches/bootstrap-urban.json
- packages/bootstrap/lib/swatches/bootstrap-vintage.json
- packages/classic/lib/swatches/classic-green-dark.json
- packages/classic/lib/swatches/classic-green.json
- packages/classic/lib/swatches/classic-main-dark.json
- packages/classic/lib/swatches/classic-main.json
- packages/classic/lib/swatches/classic-opal-dark.json
- packages/classic/lib/swatches/classic-opal.json
- packages/classic/lib/swatches/classic-silver-dark.json
- packages/classic/lib/swatches/classic-silver.json
- packages/default/lib/swatches/default-blue.json
- packages/default/lib/swatches/default-green.json
- packages/default/lib/swatches/default-main-dark.json
- packages/default/lib/swatches/default-main.json
- packages/default/lib/swatches/default-nordic.json
- packages/default/lib/swatches/default-orange.json
- packages/default/lib/swatches/default-purple.json
- packages/default/lib/swatches/default-turquoise.json
- packages/default/lib/swatches/default-urban.json
fixes: https://github.com/telerik/kendo-themes/issues/3271
> fix(button): use kendo-button prefix in swatch definitions

- packages/default/scss/tabstrip/_theme.scss
Fixes: https://github.com/telerik/kendo-themes/issues/2928
> Add focus state styles for tab item

- CODEOWNERS
Automatically request reviews for docs and visual tests.
> chore: set visual tests and docs ownership

- packages/default/scss/button/_layout.scss
Fixes: https://github.com/telerik/kendo-themes/issues/3372
> fix(button): add $kendo-button-border-radius variable to layout

- .vscode/extensions.json
- lerna.json
- package.json
- packages/default/scss/gantt/_layout.scss
- scripts/setup.sh
A setup script that:
* installs the dependencies
* initializes husky
* links the packages
* runs bootstrap
**must only be run locally, not on CI**
> Themes setup

- gulpfile.js
- package-lock.json
- package.json
related to: https://github.com/telerik/kendo-theme-tasks/issues/25
> chore: update theme tasks to v1.15

- packages/bootstrap/scss/button/_variables.scss
- packages/classic/scss/button/_variables.scss
- packages/default/scss/button/_variables.scss
- packages/material/scss/button/_variables.scss
Closes: https://github.com/telerik/kendo-themes/issues/3484
> fix(button): allow $kendo-solid-button-shade-function to be customized

- packages/default/lib/swatches/index.js
required for the Sass ThemeBuilder
> fix(swatches): export ocean blue swatch

- packages/html/src/button/button-structure.json
> Аdd button structure json

- packages/bootstrap/scss/panelbar/_variables.scss
- packages/classic/scss/panelbar/_variables.scss
- packages/default/scss/panelbar/_layout.scss
- packages/default/scss/panelbar/_variables.scss
- packages/material/scss/panelbar/_variables.scss
Closes: https://github.com/telerik/kendo-themes/issues/3606
> feat(panelbar): expose $panelbar-border-style variable

- CODEOWNERS
- packages/fluent/LICENSE.md
- packages/fluent/README.md
- packages/fluent/docs/_meta.yml
@Juveniel we definitely need to tweak the readme...
> Add fluent readme and license

- build/tag-stable.sh
@tsvetomir this should do the trick.
> Check if package is private before tagging with latest

- packages/classic/scss/button/_variables.scss
- packages/default/scss/button/_variables.scss
Public issue: https://github.com/telerik/kendo-themes/issues/3863
> fix(button): add default to $button-padding-y-lg value

- packages/default/scss/toolbar/_layout.scss
- packages/default/scss/toolbar/_theme.scss
> chore(toolbar): add focus state styling for k-toolbar-item telerik/kendo#15692

- packages/fluent/scss/index.scss
- packages/fluent/scss/responsivepanel/_layout.scss
- packages/fluent/scss/responsivepanel/_theme.scss
- packages/fluent/scss/responsivepanel/_variables.scss
- packages/fluent/scss/responsivepanel/index.scss
Related to: https://github.com/telerik/kendo-themes-private/issues/3
> [Fluent] Responsivepanel

- .github/workflows/release_dev.yml
- packages/fluent/package.json
- packages/utils/scss/flex-grid/_flex-basis.scss
- packages/utils/scss/flex-grid/_flex-grow.scss
- packages/utils/scss/flex-grid/_flex-shrink.scss
* copy all.css to dist for fluent theme
* point to correct location of all.css in dist
* add compat aliases for flex grow, shrink and basis
> Small fixesx

- gulpfile.js
- packages/html-spec/package-lock.json
- packages/html-spec/package.json
- packages/html-spec/src/button/button.json
- packages/html-spec/src/button/index.js
- packages/html-spec/src/checkbox/checkbox.json
- packages/html-spec/src/checkbox/index.js
- packages/html-spec/src/combobox/combobox.json
- packages/html-spec/src/combobox/index.js
- packages/html-spec/src/icon/icon.json
- packages/html-spec/src/icon/index.js
- packages/html-spec/src/index.js
- packages/html-spec/src/list/index.js
- packages/html-spec/src/list/list.json
- packages/html-spec/src/popup/index.js
- packages/html-spec/src/popup/popup.json
Note: I moved button structure to `html/meta/button` and changed `ref` to `$ref` (which i might change again if it's an issue).
@rkirilov @tsvetomir
> Combobox structure

- packages/default/scss/editor/_layout.scss
closes: https://github.com/telerik/kendo-themes/issues/4007
> [Editor] When in readonly mode the inner table content is resizable

- packages/default/scss/action-sheet/_layout.scss
- packages/fluent/scss/action-sheet/_layout.scss
Needed for css as less transpilation.
> Use clamp instead of max for sizing action sheet container

- packages/bootstrap/scss/pdf-viewer/_index.scss
- packages/classic/scss/pdf-viewer/_index.scss
- packages/default/scss/pdf-viewer/_index.scss
- packages/material/scss/pdf-viewer/_index.scss
Fixes: https://github.com/telerik/kendo-themes/issues/4044
> fix(pdfviewer): add utils dependancy

- packages/default/scss/spreadsheet/_layout.scss
- packages/default/scss/spreadsheet/_theme.scss
https://github.com/telerik/kendo/issues/16396 - needs overflow: hidden on the spreadsheet fixed container
https://github.com/telerik/kendo/pull/16387/files — a new `k-spreadsheet-disabled-mask` class has been added which basically needs position: absolute.
> Spreadsheet fixes

- packages/bootstrap/scss/calendar/_variables.scss
- packages/classic/scss/calendar/_variables.scss
- packages/default/scss/calendar/_variables.scss
- packages/material/scss/calendar/_variables.scss
related to: https://github.com/telerik/kendo-themes/commit/5fdd61b6100850d426ffda00491533c24cf6e194
> fix(calendar): incorrect default view width with week column

- packages/default/scss/notification/_layout.scss
- packages/fluent/scss/notification/_layout.scss
> fix(notification): add z-index to guarantee notifications stay on top

- .github/workflows/nuget_publish.yml
> Include swatches in nuget dist

- packages/bootstrap/scss/switch/_index.scss
- packages/classic/scss/switch/_index.scss
- packages/default/scss/switch/_index.scss
- packages/material/scss/switch/_index.scss
fixes https://github.com/telerik/kendo-themes/issues/4074
> fix(switch): missing border utility dependency

- packages/bootstrap/scss/treelist/_index.scss
- packages/classic/scss/treelist/_index.scss
- packages/default/scss/treelist/_index.scss
- packages/material/scss/treelist/_index.scss
fixes https://github.com/telerik/kendo-themes/issues/3703
> fix(treelist): missing text utility dependency

- packages/default/scss/input/_layout.scss
- packages/fluent/scss/input/_layout.scss
- packages/nouvelle/scss/input/_layout.scss
> Native textarea should have a scrollbar by default

- .github/workflows/publish_nuget.yml
Sets up a local feed in order to pass the username and token.
> Fix NuGet publishing

- packages/bootstrap/scss/dataviz/_variables.scss
- packages/classic/scss/dataviz/_variables.scss
- packages/default/scss/dataviz/_layout.scss
- packages/default/scss/dataviz/_variables.scss
- packages/material/scss/dataviz/_variables.scss
See https://github.com/telerik/web-components-ux/issues/615
> Update chart tooltip transition

- packages/bootstrap/scss/treelist/_theme.scss
- packages/bootstrap/scss/treelist/_variables.scss
- packages/classic/scss/treelist/_variables.scss
- packages/default/scss/treelist/_layout.scss
- packages/default/scss/treelist/_theme.scss
- packages/default/scss/treelist/_variables.scss
- packages/html-spec/src/index.js
- packages/html-spec/src/treelist/index.js
- packages/html-spec/src/treelist/treelist.json
- packages/material/scss/treelist/_layout.scss
- packages/material/scss/treelist/_theme.scss
- packages/material/scss/treelist/_variables.scss
closes: https://github.com/telerik/kendo-themes-private/issues/47
> TreeList unified rendering

- packages/html-spec/src/index.js
> chore(html-spec): require existing modules in index

- packages/fluent/docs/customization-charts.md
- packages/fluent/docs/customization.md
- packages/fluent/scss/dataviz/_layout.scss
- packages/fluent/scss/dataviz/_variables.scss
Fixes: https://github.com/telerik/kendo-themes/issues/4054
> Fluent Charts should respect series color variables

- packages/default/scss/colorgradient/_layout.scss
- packages/default/scss/icons/_layout.scss
- packages/default/scss/input/_layout.scss
- packages/fluent/scss/colorgradient/_layout.scss
- packages/fluent/scss/icon/_layout.scss
- packages/fluent/scss/input/_layout.scss
A few adjustments are needed, because of the new wrapper element introduced in Kendo Angular.
> fix(icon): adjust selectors for the new k-icon-wrapper-host element

- packages/default/scss/button/_layout.scss
- packages/fluent/scss/button/_layout.scss
continuation of https://github.com/telerik/kendo-themes/pull/4208
> fix(button): adjust selector for the new k-icon-wrapper-host element

- packages/bootstrap/scss/grid/_theme.scss
fixes: https://github.com/telerik/kendo-themes/issues/4253
> fix(pager): remove grid pager overrides in bootstrap

- .github/workflows/publish_npm.yml
- .github/workflows/publish_npm_dev.yml
- .github/workflows/publish_nuget.yml
- lib/variables.scss
- packages/default/docs/customization-common.md
- packages/default/docs/customization-component.md
- packages/default/docs/customization-typography.md
- packages/default/docs/customization.md
- packages/default/scss/_variables.scss
- scripts/resolve-variables.js
- scripts/sassdoc.js
related to: https://github.com/telerik/kendo-design-system/issues/157
Note: if a group is not specified, but a comment starting with /// is added, the var will be added to the 'common' group
> Sassdoc data publish to npm

- packages/bootstrap/scss/floating-label/_variables.scss
- packages/classic/scss/floating-label/_variables.scss
- packages/default/scss/floating-label/_layout.scss
- packages/default/scss/floating-label/_variables.scss
- packages/fluent/docs/customization-floating-label.md
- packages/fluent/docs/customization.md
- packages/fluent/scss/floating-label/_layout.scss
- packages/fluent/scss/floating-label/_variables.scss
- packages/material/scss/floating-label/_variables.scss
> Expose floating label max-width

- packages/default/scss/editor/_layout.scss
- packages/fluent/scss/editor/_layout.scss
related to https://github.com/telerik/kendo-angular/issues/3934
> fix(editor): remove editor z-index

- packages/core/docs/customization.md
- packages/core/scss/functions/_map.import.scss
- packages/utils/docs/customization.md
- packages/utils/scss/_variables.scss
- packages/utils/scss/background/_background-clip.scss
- packages/utils/scss/background/index.import.scss
- packages/utils/scss/effects/_opacity.scss
- packages/utils/scss/effects/index.import.scss
- packages/utils/scss/filter/_backdrop.scss
- packages/utils/scss/filter/index.import.scss
- packages/utils/scss/index.import.scss
- packages/utils/scss/layout/_box-sizing.scss
- packages/utils/scss/layout/_columns.scss
- packages/utils/scss/layout/_display.scss
- packages/utils/scss/layout/_object-fit.scss
- packages/utils/scss/layout/_object-position.scss
- packages/utils/scss/layout/_overflow.scss
- packages/utils/scss/layout/_placement.scss
- packages/utils/scss/layout/_position.scss
- packages/utils/scss/layout/index.import.scss
- packages/utils/scss/svg/_fill.scss
- packages/utils/scss/svg/_stroke.scss
- packages/utils/scss/svg/index.import.scss
- packages/utils/scss/typography/_list-style.scss
- packages/utils/scss/typography/_text-decoration.scss
- packages/utils/scss/typography/_vertical-align.scss
- packages/utils/scss/typography/index.import.scss
related https://github.com/telerik/kendo-themes-private/issues/84
related https://github.com/telerik/kendo-themes-private/issues/77
DO NOT MERGE until the `utils-extend-docs` branch is rebased with this one, taking the last changes.
> Extend Utils package

- packages/bootstrap/docs/customization-progressbar.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/progressbar/_variables.scss
- packages/material/scss/progressbar/_theme.scss
Fixes: https://github.com/telerik/kendo-themes/issues/4349
> Fix Progressbar indeterminate animation in Bootstrap and Material

- packages/html/src/dropdowngrid/dropdowngrid.tsx
- tests/dropdowngrid/dropdowngrid-flat.html
- tests/dropdowngrid/dropdowngrid-outline.html
- tests/dropdowngrid/dropdowngrid.html
related to https://github.com/telerik/kendo-themes-private/issues/69
The rendering in the above issue and the one in the visual tests are not consistent which might be confusing.
> test(dropdowngrid): update rendering

- package.json
- packages/html/package.json
- packages/html/scripts/build-tests.js
see https://github.com/evanw/esbuild/releases/tag/v0.17.0
> chore: remove deprecated esbuild watch mode

- packages/default/scss/input/_layout.scss
- packages/fluent/scss/input/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/4399
> fix(input): missing border of the searchbox element

- packages/bootstrap/docs/customization-list.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/list/_variables.scss
- packages/classic/docs/customization-list.md
- packages/classic/docs/customization.md
- packages/classic/scss/list/_variables.scss
- packages/default/docs/customization-list.md
- packages/default/docs/customization.md
- packages/default/scss/list/_layout.scss
- packages/default/scss/list/_variables.scss
- packages/fluent/docs/customization-list.md
- packages/fluent/docs/customization.md
- packages/fluent/scss/list/_layout.scss
- packages/fluent/scss/list/_variables.scss
- packages/material/docs/customization-list.md
- packages/material/docs/customization.md
- packages/material/scss/list/_variables.scss
fixes https://github.com/telerik/kendo-themes/issues/4449
> fix(list): missing font-family property

- packages/default/scss/pdf-viewer/_layout.scss
- packages/fluent/scss/pdf-viewer/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/4477
> fix(pdf-viewer): wrong cursor in search panel

- packages/fluent/scss/editor/_theme.scss
Closes: https://github.com/telerik/kendo-themes/issues/4484
> fix(editor): fix insert table styles in fluent

- packages/fluent/README.md
This PR updates the wrong/outdated info in the "Importing" section in the README.
> chore(fluent): update importing section in readme

- .github/workflows/publish_nuget.yml
https://github.com/telerik/kendo-themes/actions/runs/5107303413/jobs/9180087200
> ci: fix failing nuget publish

- packages/bootstrap/docs/customization-input.md
- packages/bootstrap/docs/customization.md
Needed due to changes introduced [here](https://github.com/telerik/kendo-themes/pull/4580)
> chore: regen docs

- packages/default/scss/scrollview/_layout.scss
- packages/fluent/scss/scrollview/_layout.scss
Related to: https://github.com/telerik/kendo-themes-private/issues/141#issuecomment-1649932944
> chore(scrollview): scope animations to k-scrollview-animate

- packages/html/src/textbox/templates/textbox-prefix.tsx
- packages/html/src/textbox/templates/textbox-suffix.tsx
- tests/textbox/textbox-flat.html
- tests/textbox/textbox-outline.html
- tests/textbox/textbox-solid.html
Related to: https://github.com/telerik/web-components-planning/issues/136
> chore(html): remove extra wrappers from textbox templates

- packages/html/src/dialog/index.ts
- packages/html/src/dialog/templates/dialog-modal.tsx
- packages/html/src/dialog/templates/dialog-normal.tsx
- packages/html/src/dialog/tests/dialog-action-buttons.tsx
- packages/html/src/dialog/tests/dialog-in-window.tsx
- packages/html/src/dialog/tests/dialog-modal.tsx
- packages/html/src/dialog/tests/dialog-theme-colors.tsx
- packages/html/src/dialog/tests/dialog.tsx
- packages/html/src/filemanager/tests/filemanager-dialogs.tsx
Add common Dialog templates and simplify tests.
> chore: add dialog templates

- packages/html/src/listbox/listbox.spec.tsx
Added a spec capability for necessary icons for this component.
> chore(html): add support for more icons in Listbox spec

- packages/html/src/index.ts
> chore(html): export progressbar

- packages/html/src/index.ts
Export Listview component & stub **Data management** section with further components.
> chore(html): export listview

- packages/default/scss/icons/_layout.scss
- packages/fluent/scss/icon/_layout.scss
fixes: https://github.com/telerik/kendo-themes/issues/4717
> fix(icon): modifier does not have the correct size

- packages/html/src/tilelayout/index.ts
- packages/html/src/tilelayout/templates/tilelayout-normal.tsx
- packages/html/src/tilelayout/tests/tilelayout-resizing.tsx
- packages/html/src/tilelayout/tests/tilelayout.tsx
Adds common templates for the TileLayout component
> chore: add tilelayout templates

- packages/html/src/filter/index.ts
- packages/html/src/filter/templates/filter-normal.tsx
- packages/html/src/filter/tests/filter.tsx
Adds common templates for the Filter component and simplify tests
> chore: add filter templates

- packages/html/src/editor/templates/editor-normal.tsx
- packages/html/src/editor/tests/editor.tsx
Add default items to the Editor normal template
> chore: add default items to the normal template

- packages/html/src/floating-label/templates/floating-label-normal.tsx
Add default content to the FloatingLabel normal template
> chore: add default content to the Floating label normal template

- packages/html/src/dialog/templates/dialog-normal.tsx
Add default items to the Dialog normal template
> chore: add default content to the Dialog normal template

- packages/html/src/index.ts
Exported complete components & added components in the Misc category.
> chore(html): export & stub further components

- packages/bootstrap/docs/customization-card.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/card/_variables.scss
- packages/classic/docs/customization-card.md
- packages/classic/docs/customization.md
- packages/classic/scss/card/_variables.scss
- packages/default/docs/customization-card.md
- packages/default/docs/customization.md
- packages/default/scss/card/_variables.scss
- packages/fluent/docs/customization.md
- packages/fluent/scss/card/_variables.scss
- packages/material/docs/customization-card.md
- packages/material/docs/customization.md
- packages/material/scss/card/_variables.scss
Add group variables for the **Card** component for [ **bootstrap, default, classic, material, fluent** ] theme.
> chore: edit card variables

- packages/default/scss/slider/_layout.scss
related to https://github.com/telerik/kendo-angular-private/pull/1492
> fix(slider): missing animation in rtl mode

- packages/default/scss/grid/_layout.scss
- packages/fluent/scss/grid/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/4702
> fix(grid): edit buttons misalignment

- packages/default/scss/listbox/_layout.scss
- packages/fluent/scss/listbox/_layout.scss
fixes: https://github.com/telerik/kendo-themes/issues/4704
> Fix listbox overlapping

- packages/bootstrap/docs/customization-skeleton.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/skeleton/_variables.scss
- packages/classic/docs/customization-skeleton.md
- packages/classic/docs/customization.md
- packages/classic/scss/skeleton/_variables.scss
- packages/default/docs/customization-skeleton.md
- packages/default/docs/customization.md
- packages/default/scss/skeleton/_variables.scss
- packages/fluent/docs/customization.md
- packages/fluent/scss/skeleton/_variables.scss
- packages/material/docs/customization-skeleton.md
- packages/material/docs/customization.md
- packages/material/scss/skeleton/_variables.scss
- packages/nouvelle/docs/customization-skeleton.md
- packages/nouvelle/docs/customization.md
- packages/nouvelle/scss/skeleton/_variables.scss
Adds variables description to the Skeleton component.
> chore: add skeleton variables description

- packages/default/scss/prompt/_layout.scss
- packages/fluent/scss/prompt/_layout.scss
- packages/html/src/prompt/index.ts
- packages/html/src/prompt/prompt-content.tsx
- packages/html/src/prompt/prompt-view.tsx
- packages/html/src/prompt/templates/prompt-more-actions.tsx
- packages/html/src/prompt/templates/prompt-normal.tsx
- packages/html/src/prompt/templates/prompt-output.tsx
- packages/html/src/prompt/templates/prompt-popup.tsx
- packages/html/src/prompt/templates/prompt-settings.tsx
- packages/html/src/prompt/templates/prompt-suggestions.tsx
- tests/prompt/prompt-more-actions.html
- tests/prompt/prompt-normal.html
- tests/prompt/prompt-output.html
allows to render view content dynamically, or have all views rendered
> chore(prompt): scope views content

- packages/default/scss/input/_layout.scss
- packages/fluent/scss/input/_layout.scss
Refactors separator styles for backward compatibility.
> chore: refactor input separator styles

- packages/html/src/filemanager/filemanager-listview.spec.tsx
- packages/html/src/listview/listview.spec.tsx
- packages/html/src/listview/tests/listview-layout.tsx
- packages/html/src/listview/tests/listview.tsx
- tests/listview/listview-layout.html
- tests/listview/listview.html
The `layout` property is available in jQuery only and its default value is `null`:
https://docs.telerik.com/kendo-ui/api/javascript/ui/listview/configuration/layout
> test(listview): update spec and visual tests

- packages/bootstrap/docs/customization-spreadsheet.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/spreadsheet/_variables.scss
- packages/classic/docs/customization-spreadsheet.md
- packages/classic/docs/customization.md
- packages/classic/scss/spreadsheet/_variables.scss
- packages/default/docs/customization-spreadsheet.md
- packages/default/docs/customization.md
- packages/default/scss/spreadsheet/_variables.scss
- packages/fluent/docs/customization-spreadsheet.md
- packages/fluent/docs/customization.md
- packages/fluent/scss/spreadsheet/_variables.scss
- packages/material/docs/customization-spreadsheet.md
- packages/material/docs/customization.md
- packages/material/scss/spreadsheet/_variables.scss
Adds variable descriptions for the Spreadsheet component.
> chore: add spreadsheet variable descriptions

- packages/default/scss/table/_layout.scss
- packages/fluent/scss/table/_layout.scss
fixes: https://github.com/telerik/kendo-themes/issues/4909
> fix(table): table-list group row is misaligned in safari

- packages/html/src/drawer/drawer-content.spec.tsx
- packages/html/src/drawer/drawer.spec.tsx
We should be able to set custom classNames to .k-drawer
> chore: provide an option to set custom className

- packages/default/scss/spreadsheet/_layout.scss
- packages/fluent/scss/spreadsheet/_layout.scss
- packages/html/src/spreadsheet/templates/spreadsheet-normal.tsx
- packages/html/src/spreadsheet/tests/spreadsheet-cell-contextmenu.tsx
- packages/html/src/spreadsheet/tests/spreadsheet-filtering.tsx
- packages/html/src/spreadsheet/tests/spreadsheet-formula.tsx
- packages/html/src/spreadsheet/tests/spreadsheet-jquery.tsx
- packages/html/src/spreadsheet/tests/spreadsheet-row-contextmenu.tsx
- packages/html/src/spreadsheet/tests/spreadsheet-sheets-bar.tsx
- packages/html/src/spreadsheet/tests/spreadsheet-tools.tsx
- packages/html/src/spreadsheet/tests/spreadsheet.tsx
- tests/spreadsheet/spreadsheet-cell-contextmenu.html
- tests/spreadsheet/spreadsheet-filtering.html
- tests/spreadsheet/spreadsheet-formula.html
- tests/spreadsheet/spreadsheet-jquery.html
- tests/spreadsheet/spreadsheet-row-contextmenu.html
- tests/spreadsheet/spreadsheet-sheets-bar.html
- tests/spreadsheet/spreadsheet-tools.html
- tests/spreadsheet/spreadsheet.html
Motivation: resolve inconsistency with other components, where the default width set from the theme is 100%.
> Set default Spreadsheet width to fit container

- packages/utils/scss/transform/_rotate.scss
- packages/utils/scss/transform/_scale.scss
- packages/utils/scss/transform/_skew.scss
- packages/utils/scss/transform/_translate.scss
Resolves https://sass-lang.com/documentation/breaking-changes/css-function-mixin/
> fix(utils): resolve dart-sass warning for naming functions and mixins

- .github/workflows/publish_npm.yml
- .github/workflows/publish_npm_dev.yml
- packages/bootstrap/sass-swatches.config.js
- packages/classic/sass-swatches.config.js
- packages/default/sass-swatches.config.js
- packages/fluent/sass-swatches.config.js
- packages/material/sass-swatches.config.js
- packages/nouvelle/sass-swatches.config.js
resolves: https://github.com/telerik/kendo-themes-private/issues/63
// cc @dimodi
> Add compiled swatches to cdn

- gulpfile.js
- packages/bootstrap/lib/swatches/bootstrap-main-dark.json
- packages/default/lib/swatches/default-main-dark.json
- packages/fluent/lib/swatches/fluent-main-dark.json
- packages/material/lib/swatches/material-main-dark.json
related to https://github.com/telerik/kendo-themes-private/issues/235
> Update dark swatches

- packages/fluent/docs/index.md
- packages/material/docs/index.md
related to https://github.com/telerik/kendo-angular-private/issues/2522
> docs: fix Angular related links

- packages/bootstrap/docs/customization-chart-wizard.md
- packages/bootstrap/docs/customization.md
- packages/bootstrap/scss/chart-wizard/_variables.scss
- packages/classic/docs/customization-chart-wizard.md
- packages/classic/docs/customization.md
- packages/classic/scss/chart-wizard/_variables.scss
- packages/default/docs/customization-chart-wizard.md
- packages/default/docs/customization.md
- packages/default/scss/chart-wizard/_variables.scss
- packages/material/docs/customization-chart-wizard.md
- packages/material/docs/customization.md
- packages/material/scss/chart-wizard/_variables.scss
- packages/material/scss/core/color-system/_swatch.scss
Addresses compilation issues reported in [1658306](https://supportheroes.telerik.com/ticket/1658306)
> Fix compilation issues

- packages/default/scss/editor/_layout.scss
- packages/fluent/scss/editor/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/5068
> fix(editor): table resizing tool misalignment in non-iframe mode

- packages/core/docs/customization-color-system.md
- packages/core/docs/customization.md
- packages/core/scss/color-system/_swatch.scss
- packages/default/docs/customization-color-system.md
- packages/default/docs/customization.md
- packages/utils/docs/customization-color-system.md
- packages/utils/docs/customization.md
add missing subGroup, property metadata for the $kendo-colors map
> fix: kendo-colors metadata

- packages/bootstrap/scss/dataviz/_variables.scss
- packages/classic/scss/dataviz/_variables.scss
- packages/default/scss/dataviz/_layout.scss
- packages/default/scss/dataviz/_theme.scss
- packages/default/scss/dataviz/_variables.scss
- packages/fluent/docs/customization-charts.md
- packages/fluent/docs/customization.md
- packages/fluent/scss/dataviz/_layout.scss
- packages/fluent/scss/dataviz/_theme.scss
- packages/fluent/scss/dataviz/_variables.scss
- packages/html/src/chart-wizard/templates/chart-wizard-normal.tsx
- packages/html/src/chart/tests/chart.tsx
- packages/material/scss/dataviz/_variables.scss
- tests/chart-wizard/chart-wizard.html
- tests/chart/chart.html
closes: [#295](https://github.com/telerik/kendo-themes-private/issues/295)
> feat(dataviz): enable css variable support

- package-lock.json
- packages/bootstrap/package.json
- packages/classic/package.json
- packages/material/package.json
related to [#305](https://github.com/telerik/kendo-themes-private/issues/305)
> chore: remove kendo-theme-default from dependencies

- packages/material/lib/swatches/index.js
- packages/material/lib/swatches/material-2-dark.json
- packages/material/lib/swatches/material-2.json
Light and Dark color swatches for Material 2
> feat(material): add light and dark color swatches for Material 2

- packages/core/scss/styles/_base.scss
Closes https://github.com/telerik/kendo-themes/issues/5458
> fix: disabled styles globally affect all elements

- packages/utils/docs/customization.md
- packages/utils/scss/accessibility/_screen-readers.scss
- packages/utils/scss/background/_background-color.scss
- packages/utils/scss/border/_border-color.scss
- packages/utils/scss/effects/_opacity.scss
- packages/utils/scss/elevation/index.import.scss
- packages/utils/scss/flex-grid/_flex-direction.scss
- packages/utils/scss/flex-grid/_gap.scss
- packages/utils/scss/flex-grid/_grid-column-start-end.scss
- packages/utils/scss/flex-grid/_grid-row-start-end.scss
- packages/utils/scss/flex-grid/_grid-template-columns.scss
- packages/utils/scss/interactivity/_accent-color.scss
- packages/utils/scss/interactivity/_caret-color.scss
- packages/utils/scss/interactivity/_will-change.scss
- packages/utils/scss/responsive-layout/_col-gap.scss
- packages/utils/scss/responsive-layout/_col.scss
- packages/utils/scss/spacing/_margin.scss
- packages/utils/scss/spacing/_padding.scss
- packages/utils/scss/spacing/_space-between.scss
- packages/utils/scss/typography/_font-family.scss
- packages/utils/scss/typography/_font-style.scss
- packages/utils/scss/typography/_letter-spacing.scss
- packages/utils/scss/typography/_line-height.scss
- packages/utils/scss/typography/_text-color.scss
related to: https://github.com/telerik/kendo-design-system/issues/1782
> Docs missing utils

- packages/material/scss/button/_theme.scss
Closes https://github.com/telerik/kendo-themes/issues/5520
> fix(material): incorrect hover styling on disabled solid button

- packages/core/scss/components/gantt/_layout.scss
- packages/core/scss/components/imageeditor/_layout.scss
- packages/core/scss/components/scheduler/_layout.scss
- packages/core/scss/styles/_resizing.scss
Related to 
https://github.com/telerik/kendo-themes/pull/5602
https://github.com/telerik/kendo-themes/pull/5513
> fix(core): no logical properties should be used with cardinal directions
