packages/default/scss/editor/_layout.scss
related https://github.com/telerik/kendo/issues/8212
=> fix(editor): hide toolbar buttons groups with all items

packages/default/scss/dialog/_layout.scss
related https://github.com/telerik/kendo-ui-core/issues/3603
=> fix(dialog): fix close button position in titleless dialog

packages/material/docs/customization.md, packages/material/scss/_variables.scss
The new values match the default colors from https://material.angular.io .
This simplifies uses of Kendo UI alongside the Google Material components
This also makes the migration from the LESS-based Material theme easier.
As discussed with @lkarakoleva, we should start shipping swatches along with the themes, see #36.
/cc @rkonstantinov @mvgmvg @theOrlin @joneff
=> feat: update default primary / secondary colors

packages/default/scss/grid/_layout.scss
Needed for the sake of Bootstrap 4 compatibility. See ticket 1154845.
=> fix(grid): explicitly declare box sizing to non-locked Grid content

packages/default/scss/grid/_layout.scss
This PR ~fixes~  tries fix to the filter row left double border ->
=> fix(grid): fix grid filter row double border

packages/default/scss/scrollview/_layout.scss
currently content in templates is blocked from interaction, which limits the usefulness of the component
see #32, telerik/kendo-angular#493, telerik/kendo-angular#1311
=> fix(scrollview): allow interaction in templates

packages/default/scss/grid/_layout.scss
The locked content always has a size, and should not be allowed to grow.
This change fixes problems when the ng grid is initialized in a hidden container.
See https://github.com/telerik/kendo-angular-grid/pull/516
Reported in ticket 1156102
=> fix(grid): improve layout calculation in hidden containers

packages/material/docs/customization.md, packages/material/scss/_variables.scss
The Series-A color did not match the current primary color leading to inconsistencies. Consulted with @lkarakoleva and switched the series' colors around. Soon to be reflected in the designs.
=> fix(charts): update series colors to match current primary

packages/default/scss/splitter/_layout.scss
In IE10, flex children should not be `display:inline`, which is the case for angular panes (which are custom elements).
see https://github.com/telerik/kendo-angular/issues/1408
=> fix(splitter): set pane layout for IE10

packages/default/docs/customization.md, packages/default/scss/_variables.scss, packages/default/scss/grid/_theme.scss
Most notably, this PR exposes the `$grid-alt-bg` variable to customers who want to customize the alt row  background.
=> Docs improvements

packages/default/scss/menu/_layout.scss
related https://github.com/telerik/kendo-themes/issues/78
=> chore(menu): remove resetting padding for the second sub-menu level

packages/default/scss/card/_layout.scss
If I understand correctly, the placeholders yield no rules, so they cannot be extended. Making the extends optional seems to remedy the problem.
See https://github.com/telerik/kendo-themes/issues/157
=> fix: build error with enable-rounded:false

packages/default/scss/pivotgrid/_layout.scss
Closes https://github.com/telerik/kendo-theme-default/issues/647
At the end it's an ugly hack, but works correctly in IE 11 without breaking anything else.
=> fix(pivotgrid): pivotgrid stretches beyond container in ie 11

packages/material/docs/index.md
To use the Material theme as shown on the site, the Roboto font needs to be loaded. This update shows how to do that.
@joneff it is unexpected that the `$font-family` variable does not set the font to the `.k-widget` class, do you think that it should? It is either that or we should fix the misleading docs:
=> docs: note that the Roboto font need to be loaded

packages/default/scss/grid/_layout.scss
see https://github.com/telerik/kendo-angular/issues/1688
=> fix(grid): focus outline is visible in Chrome

packages/default/scss/button/_layout.scss, packages/default/scss/calendar/_layout.scss, packages/default/scss/card/_layout.scss, packages/default/scss/common/_forms.scss, packages/default/scss/datetime/_layout.scss, packages/default/scss/editor/_layout.scss, packages/default/scss/grid/_layout.scss, packages/default/scss/numerictextbox/_layout.scss, packages/default/scss/tabstrip/_layout.scss
fixes #362 and other flex related bugs, like tabstrip misalignment in edge and IE 11
=> fix: switch from flex '1 1 0' to '1 1 auto' for ie 11 and edge

packages/default/package.json, packages/material/package.json
`npm run swatches` was not working correctly
=> chore: fix typo in build tasks

packages/default/scss/splitter/_layout.scss
flex-basis is insufficient to make the pane fully collapse, so the flex property should be forced to shrink
see https://github.com/telerik/kendo-angular/issues/1978
=> fix(splitter): collapsed panes take visible space

packages/default/scss/dropdowngrid/_layout.scss
The sass counter part of  telerik/kendo@3788274dd1393a4bce8fa04602edbac1bbb03114
Fixes telerik/kendo-ui-core#4663
=> fix(dropdowngrid): column width is not respected when virtualization is enabled

packages/default/scss/dialog/_layout.scss
There should be no spacing between stretched buttons, regardless of orientation, but there is:
=> fix(dialog): there should be no spacing between streched buttons in rtl

packages/bootstrap/package.json, packages/default/package.json, packages/material/package.json, packages/material/scss/swatches/pink-bluegrey-dark.scss, packages/theme-tasks/.eslintrc, packages/theme-tasks/lib/tasks/sass.js, packages/theme-tasks/lib/utils/nodesass-packageimporter.js, packages/theme-tasks/package.json
Previously, swatches only built the first swatch, due to heavy optimizations on our side and the way gulp works.
I've extended the code to allow building without optimizations, which does take some more time.
=> Fix swatches and add them to npm package

packages/default/scss/grid/_layout.scss
related to: https://github.com/telerik/kendo-ui-core/issues/4291
=> Grid: pdf export layout when pageSize is not set

packages/default/scss/grid/_layout.scss
targets: https://github.com/telerik/kendo-themes/issues/591
=> Grouping header text overflows with frozen columns

packages/default/scss/common/_base.scss
As discussed with @joneff I am adding the `k-no-click` class. We are going to use this class when we cannot assign the `k-state-disabled`, however, the user should not interact with the element.
cc: @elena-gancheva @TeyaVes @Juveniel
=> Add k-no-click class styles

packages/bootstrap/scss/colorpicker/_theme.scss, packages/default/scss/colorpicker/_layout.scss, packages/default/scss/colorpicker/_theme.scss
* Applied the `.k-state-hover` also to `.k-picker-wrap:hover` - no point in using js to achieve the hover effect.
* While on the ColorPicker topic: the styles of the `.k-item` elements inside the ColorPalette are inconsistent when the palette is used as a standalone component and when it's used in the ColorPicker component (inside a popup), as you can see below. The `cursor: pointer` is applied from the popup styles (`.k-popup .k-item`). Perhaps we should apply that style for the standalone palette as well. Raising the question here, as there's no point in opening a separate PR for this in my opinion.
=> ColorPicker: wrapper hover styles not applied

packages/bootstrap/docs/customization.md, packages/bootstrap/scss/_variables.scss
See https://github.com/telerik/kendo-themes/issues/733
=> docs: fix bootstrap mismatching variable descriptions

packages/material/scss/popup/_layout.scss, tests/visual/colorpicker.html
See: https://github.com/telerik/kendo-themes/issues/740
The popup element cannot be targeted by the existing selector because it is rendered dynamically and can exist in a different HTML structure. 
An additional class of the ColorPicker component has to be added. Class name: `k-colorpicker-popup`. 
This class sets the padding of the targeted element to zero and thus removes the additional padding of the popup in the Material theme.
=> fix(colorpicker): remove additional padding for material theme

packages/default/scss/adaptive/_layout.scss
Targets: https://github.com/telerik/kendo-themes/issues/721
=> Cannot select text if the Grid is inside Splitter pane

packages/material/scss/grid/_layout.scss
targets: https://github.com/telerik/kendo-themes/issues/761
=> Grid: Material filter menu wrong font-weight

packages/default/package.json
Targeting WS-2019-0103 -- Handlebars.js before 4.1.0 has Remote Code Execution (RCE)
=> chore: update handlebars dependency due to security issue

packages/default/scss/treelist/_layout.scss
Styles needed for treelist sticky header
=> fix: improve sticky headers of treelist

packages/default/scss/gantt/_layout.scss, packages/default/scss/gantt/_theme.scss, packages/material/scss/gantt/_layout.scss, packages/material/scss/gantt/_theme.scss
Because of an issue reported by Compliance Sherrif (https://www.w3.org/TR/WCAG20-TECHS/H43), I had to change the `<thead>` and `<th>` elements in the header of the Gantt Timeline to `<tbody>` and `<td>`. In order to keep the styling as it is now, I have to introduce some new rules for the Gantt widget.
=> Improve Gantt Timeline Header Accessibility

packages/default/scss/progressbar/_layout.scss
Related to kendo-jquery: when no initial size (width, height) is set, the animations start from 100% instead of 0.
=> fix(progressbar): set initial size to progress so it animates smoothly

packages/theme-tasks/lib/tasks/sass.js, packages/theme-tasks/lib/utils/nodesass-packageimporter.js
* rework sass importer logic so it handles local files imports, not only ~
* add utility method to sass import to conveniently reset imported paths, thus enabling watch again
=> Improve build time and enable watch for themes

packages/theme-tasks/lib/tasks/sass.js, packages/theme-tasks/lib/utils/nodesass-packageimporter.js
dart-sass compilation couldn't be fast, because we couldn't use caching properly. Reason for that being how dart-sass and node-sass treat our `EMPTY_FILE` descriptor. Previously, node-sass treated it OK, but dart-sass was complaining. It turns out `EMPTY_FILE` needs to be blank object with no fields!
Some data:
```bash
$ gulp sass
[16:19:37] Using gulpfile ~/work/kendo-themes/packages/bootstrap/gulpfile.js
[16:19:37] Starting 'sass'...
[16:19:38] Finished 'sass' after 973 ms
$ gulp dart
[16:19:51] Using gulpfile ~/work/kendo-themes/packages/bootstrap/gulpfile.js
[16:19:51] Starting 'dart'...
[16:20:15] Finished 'dart' after 23 s
$ gulp sass
[16:21:35] Using gulpfile ~/work/kendo-themes/packages/bootstrap/gulpfile.js
[16:21:35] Starting 'sass'...
[16:21:36] Finished 'sass' after 957 ms
$ …
```
=> fix: speedup dart-sass compilation

packages/theme-tasks/gulpfile.js, packages/theme-tasks/package.json
Note: Obviously, this needs to be rebased after #904 is merged. Pay attention to the last two commits.
It's been an issue for a while now, compiling the themes outside of the scope of our development takes too much time. That's why I've added functionality to inline / flatten / squash / whatever the themes in a single mostly self-contained file that can be included.
The results are sub 1s compile time.
Since we are not using `_index.scss` convention anywhere, we could actually have the current `_all.scss` files renamed to `_index.scss` and the have `_all.scss` generated. We could even do it for components.
~~I am open to suggestions how to name the tasks. `inline-sass-files` doesn't sound right. Perhaps "flatten"?~~ Renamed task to `flatten-sass-files`.
* fixes #423 and probably others …
=> Flatten theme files for dist

packages/default/scss/editor/_layout.scss
see telerik/kendo-angular#2227
=> fix(editor): whitespaces are trimmed at the end of a text in FF

packages/default/scss/grid/_layout.scss
Adds a dedicated class for the standalone column menu that overrides the default position.
The attempt from #1051 relied on the header content being wrapped in `<a class="k-link">` which is not the case if the column is not sortable.
This approach also allows placing the column menu outside the Grid.
=> fix(grid): add styles for standalone column menu

packages/bootstrap/scss/_variables.scss, packages/default/scss/_variables.scss, packages/default/scss/grid/_layout.scss, packages/default/scss/upload/_layout.scss, packages/material/scss/_variables.scss
To ensure correct calc expression there must be space around operators (`-`, `+`, `*`, `/`)
=> fix: add whitespace around operators in calc expressions

packages/default/scss/tabstrip/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/1039
=> fix(tabstrip): remove default browser outline

packages/bootstrap/docs/customization.md, packages/bootstrap/scss/_variables.scss, packages/default/docs/customization.md, packages/default/scss/_variables.scss, packages/default/scss/functions/_colors.scss, packages/material/docs/customization.md, packages/material/scss/_variables.scss
When creating swatches, we must specify `$color-level-step` and `$yiq-` vars, which seems counter intuitive.
To avoid this, I am moving the variables to `functions/_colors.scss` file. The downside is the intricate fallback mechanism, but we could simplify that at a later point, should we see the need to.
=> Move color variables

packages/bootstrap/scss/slider/_theme.scss, packages/default/scss/mixins/_decoration.scss, packages/default/scss/slider/_theme.scss
fixes: https://github.com/telerik/kendo-themes/issues/1177
Note: as the material theme file inherits most of the styles from the default theme, the empty URL cannot be completely removed.
=> fix(slider): background-image empty url in material theme

packages/default/scss/scheduler/_layout.scss
Hello Team,
I'd like to propose the following changes to the `.k-select` class inside the date-time pickers.
While working on the KendoReact scheduler component, we wanted to replace the current `button.k-link` + `<Calendar />` with a `<DatePicker />` component + custom renders.
The custom renders consist of:
- Removing the `k-picker-wrap`
- Removing the `dateinput`
- Adding text (formatted `Date`) inside the `a.k-select` of the DatePicker.
After applying the custom renders to the `<DatePicker />` the markup is the following:
```html
<span role="group" aria-expanded="false" class="k-widget k-datepicker">
<a role="button" class="k-select k-link" title="Toggle calendar" aria-label="Toggle calendar"> . 
<span class="k-icon k-i-calendar"></span><span class="k-sm-date-format">June 2020</span> …
```
=> Ensure widgets inside scheduler header or footer inherit font-size

packages/default/scss/gantt/_layout.scss
=> fix(gantt): exported timeline does not expand to full width in ie

packages/default/scss/gantt/_layout.scss
=> fix(gantt): align task dots vertically for IE and Edge

packages/theme-tasks/package-lock.json, packages/theme-tasks/package.json
Fixes a bug where calling `sass:flat` and `sass:swatches` sequentially will result in "empty" /dist/all.scss file. That happens in prepublish...
/cc @vstaykov @svetq FYI the bug is being fixed
=> Update @joneff/baka to mitigate caching issue when flattening files for dist

packages/default/scss/filemanager/_layout.scss
targets: telerik/kendo/issues/10923
=> fix(filemanager): view container should overflow

packages/default/scss/common/_animations.scss
fixes https://github.com/telerik/kendo-themes/issues/1597
=> fix(contextmenu): menu items cut off

packages/default/scss/calendar/_layout.scss
related to: https://github.com/telerik/kendo-themes/issues/1602
=> fix(calendar): remove outline from today button

packages/default/scss/dataviz/_index.scss
tooltip dependency is added to the chart in order for this to work as expected: https://github.com/telerik/kendo-themes/issues/1623
=> Add tooltip dependency to chart

packages/default/scss/input/_layout.scss
The issue is logged in the React repo: https://github.com/telerik/kendo-react/issues/638
=> fix(input): remove additional box shadow in Firefox browser

packages/nouvelle/.sassdocrc, packages/nouvelle/LICENSE.md, packages/nouvelle/README.md, packages/nouvelle/docs/customization-buttons.md, packages/nouvelle/docs/customization-color-system.md, packages/nouvelle/docs/customization-common.md, packages/nouvelle/docs/customization-component.md, packages/nouvelle/docs/customization.md, packages/nouvelle/gulpfile.js, packages/nouvelle/package-lock.json, packages/nouvelle/package.json, packages/nouvelle/scss/_variables.scss, packages/nouvelle/scss/all.scss, packages/nouvelle/scss/button/_layout.scss, packages/nouvelle/scss/button/_theme.scss, packages/nouvelle/scss/button/_variables.scss, packages/nouvelle/scss/button/index.scss, packages/nouvelle/scss/functions/_index.scss, packages/nouvelle/scss/index.scss, packages/nouvelle/scss/mixins/_index.scss
Related to #798
* sass variables allow us to have `null` value and do not generate output when there is no need, which is not the case with css variables;
* on top of that, css variables, if not provided with fallback and have `null` value will fallback to `prop: initial`
* focus state, per se, is `null`, so should we provide a fallback to normal state?
* should we have a sort of handling of css variables, so we use either css or sass variables?
* `prop: k-var( --kendo-css-var, $kendo-sass-var )` and have a `$use-css-variables` switch...
Apart from that, it looks like it would be doable to have e theme that's based on css variables but can also benefit from sass toolchain.
=> fix(button): add initial styles for button

packages/bootstrap/scss/_variables.scss, packages/classic/scss/_variables.scss, packages/default/scss/_variables.scss, packages/default/scss/gantt/_layout.scss, packages/default/scss/gantt/_theme.scss, packages/default/scss/mixins/_gradients.scss, packages/material/scss/_variables.scss
Design here: https://github.com/telerik/kendo-ux-private/issues/154
* The Material design from above does not use the current colors for a task and selected row
=> chore(gantt): planned vs actual telerik/kendo#11149

.github/workflows/tag_stable.yml, build/constants.sh, build/foreach.sh, build/install.sh, build/tag-stable.sh
Action that adds **stable** dist-tag to themes themes. Used to denote version compatible with kendo-jquery.
Fixes #1770
=> infra: add stable release action

packages/default/scss/pivotgrid/_layout.scss
=> Pivot: row headers width in IE

build/clean.sh, build/install.sh
Ugly hack. Requires environmental `$JENKINS` variable to be set to `true`, even though there is no true `true` in bash :D
Alternatively, I could use `$CI` variable for all such cases, in case we need the same handling for all cases.
/cc @ipeshev @tsvetomir ideas?
=> Detect jenkins for clean and install jobs

packages/default/scss/utils/_position.scss
Reverses middle pos in RTL. Currently utilized in the FloatingActionButton.
related to: https://github.com/telerik/kendo-themes/issues/1948
=> fix(utils): reverse middle pos in rtl

packages/default/scss/dropdowngrid/_layout.scss
Needs for the React MultiColumnComboBox implementation. Tested and doesn't break the jQuery widget.
=> fix(multicolumncombobox): remove the horizontal scroll from popup

packages/bootstrap/scss/grid/_theme.scss, packages/default/scss/grid/_theme.scss, packages/material/scss/grid/_theme.scss
Needs for the keyboard navigation implementation in React Grid/Treelist/Gantt components.
=> feat(grid): add focus shadow to the cells on native browser focus

packages/default/scss/splitter/_layout.scss
`.k-draghandle` is bleeding high z-index because it's too generic
fixes #845
=> fix(splitter): force low z-index on splitter draghandle

packages/default/scss/tooltip/_layout.scss
Fixes: #2060
Less themes counterpart: telerik/kendo#11924
=> Apply flex grow to tooltip content so the close icon is at the correct position

packages/bootstrap/scss/toolbar/_layout.scss, packages/default/scss/toolbar/_layout.scss
Fixes #1665
Note: we do have a test, but the rendering is not correct. We should and will revise it.
=> Splitbutton in overflow should display its items vertically

packages/default/scss/tooltip/_layout.scss
fixed #1744
Needed so iframes can take as much as space as needed.
=> Tooltip content should take all available vertical space

packages/default/scss/dropdowngrid/_layout.scss, packages/default/scss/dropdowngrid/_theme.scss
https://github.com/telerik/kendo-angular-dropdowns/issues/758
Repro demo:
https://stackblitz.com/edit/angular-mwkaiw?file=app/app.component.ts
Reproducible with React's MCCB as well. https://www.telerik.com/kendo-react-ui-develop/components/dropdowns/multicolumncombobox/keyboard-navigation/
=> fix(multicolumncombobox): item k-state-hover styles not applied on hover

packages/default/scss/dataviz/_layout.scss, tests/visual/assets/scripts.js
Extracted from #2184.
The change allows to simplify the styles we use to expose css values to charts. It also reduces the amount of actual css output by a good margin.
=> Apply chart colors in tests

packages/default/scss/slider/_layout.scss
=> Ticks in vertical slider are misaligned in Safari

packages/default/scss/checkbox/_layout.scss, packages/default/scss/radio/_layout.scss
The issue can be seen on Angular Forms Guideline page: 
- https://www.telerik.com/kendo-angular-ui/components/forms/forms-guideline/#toc-form-controls
- https://www.telerik.com/kendo-angular-ui/components/forms/forms-guideline/#toc-checkboxes--radiobuttons
The reason that Angular checkboxes and radios have their labels on a new line is the difference in the rendering compared to the other suites. Here, we have a host element that is inline and there is a `<label>`, that is a block element.
=> fix(inputs): angular checkbox and radio labels on the same line

packages/default/scss/adaptive/_layout.scss
Reported from Sitefinity client (tool validation) that units are not specified for the width property.
Design ref: https://github.com/telerik/kendo-ux-private/issues/13
Note: width is not required due to [flex](https://github.com/telerik/kendo-themes/blob/86d6b6dcee890dafa0c3dc0b8cf515d0b69a1cff/packages/default/scss/adaptive/_layout.scss#L464).
=> chore: remove redundant width from adaptive timezone editor

packages/bootstrap/scss/dataviz/_variables.scss, packages/classic/scss/dataviz/_variables.scss, packages/default/scss/dataviz/_layout.scss, packages/default/scss/dataviz/_variables.scss, packages/material/scss/dataviz/_variables.scss
Not sure if this is the right way to do it. All existing variables either set the font family or size.
=> feat: add $chart-pane-title-font-weight variable

packages/default/scss/tilelayout/_layout.scss
By default, flex items have min-height: auto as initial value (https://drafts.csswg.org/css-flexbox/#min-size-auto). Therefore in scenarios when the content placed in the TileLayout item body component is higher than the wrapper, it overflows. Setting min-height to 0 will give users the opportunity to use vertical scroll for the long content.
=> fix: long content in item body overflows

packages/default/scss/grid/_layout.scss
targets: #2069 
Before:
After:
=> fix(grid): grid filter button cut off in IE11

packages/default/scss/dataviz/_layout.scss
Part of #2234
Use `try-shade` with default color step instead of `darken` with percentage.
=> Reduce color distance in chart component

packages/default/scss/expansion-panel/_layout.scss
Fixes https://github.com/telerik/kendo-themes/issues/2304
=> fix: ExpansionPanel with sibling has wrong top margin

packages/default/scss/datetime/_layout.scss
Due to the requirement of having the `tabindex="-1"` attribute on the `k-select` datetime elements, we need to remove the user agent default focus outline.
=> Datetime: remove k-select focus outline

packages/default/scss/calendar/_layout.scss
`box-sizing: content-box;` fixes the issue that can be seen in [this Stackblitz example](https://stackblitz.com/edit/angular-viwmso-fbz8v9) (Calendar gets bigger and bigger on each Prev/Next click), which is caused by the bootstrap reset styles.
`table-layout: auto;` fixes the issue that can be seen in [this Stackblitz example](https://stackblitz.com/edit/angular-viwmso-74ivef?file=app/app.component.ts) (currently in Firefox Developer Edition only) when animating the Prev/Next views.
=> fix(calendar): navigation animation adjustments for angular

packages/default/scss/scheduler/_layout.scss
Prevent event element from shrinking when the events container is scrollable in the Scheduler year view Tooltip.
=> chore(scheduler): prevent year view tooltip event from shrinking

packages/default/scss/grid/_layout.scss
non sticky grid header cells should slide below sticky header cells
=> Angular grid fixes

packages/default/scss/taskboard/_layout.scss
Setting overflow wrapping for pane title to prevent the text from overflowing its line box.
similar to: https://github.com/telerik/kendo-themes/pull/2425
=> chore(taskboard): set overflow wrapping for pane title

packages/default/scss/scheduler/_layout.scss
Fallback for [gap support in flex layout](https://caniuse.com/flexbox-gap).
=> chore(scheduler): add spacing to year view calendar in safari and ie

packages/default/scss/taskboard/_layout.scss
related to: #2227
The idea of this refactoring is to handle cases where the drag hint that contains a card is appended to the <body> element.
=> fix(taskboard): scope category border selector in rtl

packages/default/scss/panelbar/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/2388
The fix is related to the CSS properties [margin-inline-start](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-start) and [margin-inline-end](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-inline-end) that are not supported by IE.
=> fix(panelbar): the arrow icons are not aligned correctly in IE

docs/accessibility/Grid.md
Using the `Tab` key to focus the filter menu:
* Breaks the single tab stop principle.
* Introduces an alternative method for focusing cell content.
=> docs(a11y): update grid filter menu spec

packages/default/scss/grid/_theme.scss
related to https://github.com/telerik/kendo-themes/issues/2500
The [Grid keyboard navigation](https://www.telerik.com/kendo-angular-ui/components/grid/keyboard-navigation/) is disabled by default.
If this is the case, no `focus` styles should be applied.
=> fix(grid): do not apply pager focus styles on non-navigable grid

.github/workflows/release_dev.yml, .github/workflows/release_stable.yml
* Restricts tokens to commands that need them.
* Updates "actions/setup-node" to v2 with built-in caching.
=> chore: refactor publish workflows

.github/workflows/publish_swatches.yml
Packages pre-built CSS themes and swatches and commits them to an artifact repo for deployment.
=> chore: add workflow to publish swatches

packages/default/scss/gantt/_layout.scss
This is needed for the Kendo Angular Gantt and probably for the Blazer Gantt in the future.
=> feat(gantt): add treelist scrollable class

packages/bootstrap/README.md
@kdubious, I am removing wording regarding bootstrap version, temporarily. (As in, we need better readme)
=> Reword bootstrap theme readme to not specify bootstrap version

.github/workflows/release_dev.yml, package-lock.json, package.json, scripts/semver-dev-inc.js
Lerna is having trouble determining the correct version for dev releases. I am reckoning that has something to do with our use of `--canary` and `--no-push`. Also, there are numerous reports where that particular approach may yield inconsistent results.
Considering all themes have and must have the same version, the following trickery this should do it:
* query the dev and latest version of default theme
* compare them with `semver.gt` to get the larger (semantically newer)
* increment the result with `semver.inc`
* pass that option to lerna publish
=> Use lerna publish with predetermined version instead of --canary for dev releases

packages/bootstrap/scss/adaptive/_theme.scss, packages/material/scss/adaptive/_theme.scss
Remove legacy `k-check` styles which were not used anywhere.
=> Remove redundant styles from adaptive scheduler / grid

packages/bootstrap/scss/fab/_variables.scss, packages/classic/scss/fab/_variables.scss, packages/default/scss/fab/_variables.scss, packages/material/scss/fab/_variables.scss
calc expressions containing addition / subtraction with unitless  numbers (even 0) are invalid. Those were the last such cases.
fixes #2031
=> Do not use unitless sizes which invalidate calc expressions

packages/default/scss/splitter/_theme.scss
fixes #2143.
Changed the selector from `:active` to `:focus`, because this is the correct selector: when the splitbar is clicked it's also focused. Actually, no element can be active without being focused...
=> Style splitbar focus instead of active state

packages/bootstrap/scss/chat/_variables.scss, packages/classic/scss/chat/_variables.scss, packages/default/scss/chat/_layout.scss, packages/default/scss/chat/_variables.scss, packages/material/scss/chat/_variables.scss
fixes #1182
Note: chat should probably be 100% wide and 100% tall and the size should be determined by the container. However, that might prove breaking when it comes to existing implementations. so we are going to wait for a breaking version.
=> Expose variables to control chat width and height

packages/default/scss/gantt/_layout.scss
There was `white-space: nowrap` missing.
=> Task details tooltip should not wrap its content

packages/default/scss/pivotgrid/_layout.scss, tests/visual/src/misc/pivotgrid-settings-top.html, tests/visual/src/misc/pivotgrid.html
The change was initially requested by the React team as till now, the headers had both `th` and `td` HTML elements where `th` elements were the root cells (with bold and uppercase text styling).
This change provides a new class named `k-pivotgrid-header-root` that will be applied to the root cells (at level 0) that will apply the bolder and uppercase styling. The rest of the `th` elements will have normal font-weight and text-transform.
Please check the visual tests for more info.
cc/ @kspeyanski @ag-petrov
=> Pivotgrid headers

packages/default/scss/utils/_text.scss
The motivation for this change is that the Typography's fontSize property uses the font-size enum to apply different sizes.
=> fix: add kendo font sizes to the Bootstrap theme

packages/nouvelle/docs/_meta.yml, packages/nouvelle/docs/index.md
As part of https://github.com/telerik/katana/pull/1098 we plan to introduce the documentation for the new two themes and label them as `beta`.
=> Docs new themes tag

packages/default/scss/grid/_layout.scss
closes https://github.com/telerik/kendo-themes/issues/2773
=> fix(grid): replace hardcoded vertical border width

docs/components/checkbox/index.md, docs/components/radio/index.md
Incorrect markup causes the themes-docs site build to fail
=> chore(docs): use correct html markup for radio and checkbox docs

packages/default/scss/color-preview/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/2960
=> fix(color-preview): remove cursor pointer from preview-color element

packages/default/scss/grid/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/2576
=> fix(grid): decrease column menu icon z-index

packages/classic/README.md, packages/nouvelle/README.md, packages/nouvelle/docs/_meta.yml, packages/nouvelle/docs/index.md
Part of: https://github.com/telerik/katana/issues/1231
@nrch can you share your feedback on the Nouvelle overview description?
=> Docs updates

packages/default/scss/list/_layout.scss
item is selectable, thus changing the default cursor to pointer
targets: https://github.com/telerik/kendo-themes/issues/3108
=> fix(list): set item cursor to pointer

packages/default/scss/input/_layout.scss
targets: https://github.com/telerik/kendo-themes/issues/3107
=> fix(input): input button should not have a focus shadow

packages/default/scss/toolbar/_layout.scss
targets: https://github.com/telerik/kendo-themes/issues/3175
=> fix(editor): floating toolbar should take available width

packages/default/scss/input/_layout.scss
Fixes: https://github.com/telerik/kendo-themes/issues/3176
=> fix: reset margin for inputs and pickers direct children v5

packages/default/scss/listbox/_layout.scss, tests/visual/src/misc/listbox.html
targets: https://github.com/telerik/kendo-themes/issues/3144
This PR introduces a breaking change:
* use universal List rendering for the ListBox
```html
<div class="k-listbox k-listbox-toolbar-left">
<div class="k-listbox-toolbar">... </div>
<div class="k-list-scroller k-selectable">
<div class="k-list k-list-md">
<div class="k-list-content">
<ul class="k-list-ul">
<li class="k-list-item">
<span class="k-list-item-text">Item</span>
</li>
</ul>
</div>
</div>
</div>
</div>
```
* state classes for list items are also changed from `k-state-hover`, `k-state-selected`, etc. to `k-hover`, `k-selected`, etc.
/cc @ag-petrov, @kspeyanski
=> feat(listbox): use new list styling

packages/default/scss/listbox/_layout.scss
Fixes: https://github.com/telerik/kendo-themes/issues/3230
=> fix(listbox): display bottom border of the list container

packages/bootstrap/scss/grid/_theme.scss, packages/default/scss/grid/_theme.scss, packages/material/scss/grid/_theme.scss
Fixes: https://github.com/telerik/kendo-themes/issues/1572
=> fix(grid): remove separate hover styling on detail row container

packages/bootstrap/scss/daterangepicker/_variables.scss, packages/classic/scss/daterangepicker/_variables.scss, packages/default/scss/daterangepicker/_layout.scss, packages/default/scss/daterangepicker/_variables.scss, packages/default/scss/forms/_layout.scss, packages/material/scss/daterangepicker/_variables.scss
fixes: https://github.com/telerik/kendo-themes/issues/3209
=> fix(daterangepicker): set default width for dateinputs

docs/components/dropdowntree/index.md
this issue breaks the themes site build in /katana
=> docs: use correct markdown syntax in dropdowntree article

packages/default/scss/list/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/3388
=> fix(list): empty items have a wrong height

scripts/setup.sh
It seems that on windows `npm run setup` leaves artefacts. This change should take care of them.
=> Checkout package-lock.json after npm link

scripts/setup.sh
[Clean install](https://docs.npmjs.com/cli/v8/commands/npm-ci) in setup scripts in order to prevent package.lock update with different node versions.
=> chore: use npm ci in setup script

packages/default/scss/button/_layout.scss
Fixes issues where the icon button is stretched in flex containers.
=> fix(button): remove forced aspect ratio

packages/default/scss/input/_layout.scss
Needed for accessibility
Addresses https://github.com/telerik/k2/issues/694
=> Make kendo-popup 'pos: fixed' inside inputs and pickers so it's not clipped by overflow hidden

packages/bootstrap/scss/grid/_theme.scss, packages/default/scss/grid/_theme.scss, packages/material/scss/grid/_theme.scss
fixes: telerik/kendo-themes/issues/3604
=> Remove highlighting of header row in detail grid

packages/bootstrap/scss/daterangepicker/_variables.scss, packages/classic/scss/daterangepicker/_variables.scss, packages/default/scss/daterangepicker/_variables.scss, packages/material/scss/daterangepicker/_variables.scss
The  `$kendo-daterange-picker-input-width` variable was missing a `!default` flag and could not have been customized.
=> Expose $kendo-daterange-picker-input-width variable

packages/fluent/scss/action-buttons/index.scss, packages/fluent/scss/button/index.scss, packages/fluent/scss/calendar/index.scss, packages/fluent/scss/card/index.scss, packages/fluent/scss/core/module-system/index.scss, packages/fluent/scss/dialog/index.scss, packages/fluent/scss/forms/index.scss, packages/fluent/scss/icon/index.scss, packages/fluent/scss/input/index.scss, packages/fluent/scss/list/index.scss, packages/fluent/scss/listbox/index.scss, packages/fluent/scss/listgroup/index.scss, packages/fluent/scss/maskedtextbox/index.scss, packages/fluent/scss/messagebox/index.scss, packages/fluent/scss/multiselect/index.scss, packages/fluent/scss/notification/index.scss, packages/fluent/scss/numerictextbox/index.scss, packages/fluent/scss/overlay/index.scss, packages/fluent/scss/popup/index.scss, packages/fluent/scss/rating/index.scss, packages/fluent/scss/searchbox/index.scss, packages/fluent/scss/split-button/index.scss, packages/fluent/scss/textarea/index.scss, packages/fluent/scss/textbox/index.scss, packages/fluent/scss/timepicker/index.scss, packages/fluent/scss/typography/index.scss, packages/fluent/scss/utils/index.scss, packages/fluent/scss/window/index.scss
* require `icon` instead of `icons`, because that's the correct module name
* use spread operator for module meta in `module.register` because it expects two params
* minor tweaks in the module system to correctly report / warn about missing styles dependencies
This should resolve all warnings, as of now.
=> Resolve module system warnings

packages/default/scss/pivotgrid/_layout.scss
related to: https://github.com/telerik/kendo-themes/issues/3804
=> fix(pivotgrid): add outline none to focus cells

package-lock.json, package.json
Fixes issue with `@joneff/baka` file import paths on windows machines.
=> chore(deps): update kendo-theme-tasks to v1.17.3

.github/workflows/ci_visual.yml, .github/workflows/compile_themes.yml, .github/workflows/create_snapshots.yml
Split `create-snapshots` and `compile-themes` into separate child workflows. that way, they can be reused if needed or optimized without touching the main workflow.
=> Use child workflows for generating test assets

build/create-snapshots.mjs, package.json
Speed up snapshot by splitting the list into 8 chunks and executing in asynchronously.
On a local M1 Pro machine cuts the time from 36s to 10s which is about x4 improvement.
/cc @tsvetomir @dtopuzov
=> Snapshot chunks

packages/fluent/scss/dataviz/_layout.scss
fixes: https://github.com/telerik/kendo-themes/issues/3997
=> [DataViz] The colors of gauge track and gauge pointer are incorrect

packages/html-spec/package.json, packages/html-spec/scripts/build.js, packages/html-spec/src/button/index.js, packages/html-spec/src/checkbox/index.js, packages/html-spec/src/combobox/index.js, packages/html-spec/src/icon/index.js, packages/html-spec/src/index.js, packages/html-spec/src/list/index.js, packages/html-spec/src/popup/index.js
In this PR:
* As [import assertions](https://github.com/tc39/proposal-import-assertions) are still level 3, this causes eslint parse errors when importing JSON files. Thus, switching to require.
* Export `components.json` in dist folder.
=> Kendo HTML spec export all components

packages/default/scss/signature/_layout.scss
Related to changes implemented in: https://github.com/telerik/kendo-themes/pull/4035
=> fix(signature): remove k-signature-canvas outline on focus-visible

.github/workflows/ci_dev.yml, .github/workflows/ci_next.yml, .github/workflows/ci_unit.yml, .github/workflows/ci_visual.yml, .github/workflows/compile_themes.yml, .github/workflows/create_snapshots.yml, .github/workflows/merge_develop.yml, .github/workflows/publish_swatches.yml, .github/workflows/release_dev.yml, .github/workflows/release_next.yml, .github/workflows/release_stable.yml, .github/workflows/tag_stable.yml
Targeting a recent warning:
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions/setup-node, actions/setup-node, actions/checkout
=> Update checkout and setup-node actions to v3

packages/utils/scss/flex-grid/_gap.scss
`k-gap-x` and `k-gap-y` utility classes were missing and causing some tests in Fluent to break.
Fixes lack of column spacing in Fluent noticed in https://github.com/telerik/kendo-themes/pull/4043
=> feat(utils): add row and col gap utility classes

.github/workflows/ci_visual.yml
Related to https://github.com/actions/runner-images/issues/6399
In short: by Dec 1, `ubuntu-latest` will use `ubuntu-22.04`. That image does not have Firefox, as of yet. As a result, our builds will fail.
=> Еxplicitly download firefox in actions

.github/workflows/ci_dev.yml, .github/workflows/ci_next.yml, .github/workflows/ci_unit.yml, .github/workflows/ci_visual.yml, .github/workflows/compile_themes.yml, .github/workflows/create_snapshots.yml, .github/workflows/nuget_publish.yml, .github/workflows/publish_swatches.yml, .github/workflows/release_dev.yml, .github/workflows/release_next.yml, .github/workflows/release_stable.yml, .github/workflows/tag_stable.yml
By caching `node_modules` and skipping `npm ci` we should save some time.
@tsvetomir the way I am reading the docs, without specifying a restore key, only a full match will result in cache hit. Correct?
=> Cache root node_modules to speedup builds

docs/components/floatingactionbutton/index.md, packages/default/scss/fab/_layout.scss, packages/fluent/scss/fab/_layout.scss, packages/html/src/fab/fab.tsx, tests/fab/fab-items.html, tests/fab/fab-position.html, tests/fab/fab-size.html, tests/fab/fab-states.html, tests/fab/fab.html
The FAB shape property is obsolete and needs to be removed from the component and the demos (as it was removed from the Button).
=> Remove styles for fab shape property

packages/default/scss/gantt/_layout.scss, packages/fluent/scss/gantt/_layout.scss
A stronger selector is needed so the `white-space: nowrap;` rule can be applied, which fixes the following issue:
=> fix(gantt): add a stronger td selector

packages/default/scss/button/_layout.scss, packages/fluent/scss/button/_layout.scss
If a SVG icon is used insed icon button, due to the min-widht and height that we set to the .k-button-icon element, the SVG icon gets resized as well.
=> Button icon svg

.github/workflows/_compile-themes.yml, .github/workflows/_test-contrast.yml, .github/workflows/ci.yml, package-lock.json, package.json, scripts/test-contrast.mjs
What's changed:
* wait for themes and test assets to be compiled before running tests
* run against rendered html files instead of the react alternative
* reduce await usage
* run in parallel via max-chunks input
=> Speedup a11y tests

packages/core/docs/customization.md, packages/core/scss/functions/_color-manipulation.import.scss, packages/utils/docs/customization.md, packages/utils/scss/_variables.scss, packages/utils/scss/typography/_text-overflow.scss, packages/utils/scss/typography/index.import.scss
* streamline typography styles for text overflow and text tuncate;
* use two steps for color manipulation depending on light or dark theme.
I think the latter one can be slightly improved to take into consideration the current theme and to always use `$kendo-color-level-stop`.
I had to patch the few places where the old `k-text-ellipsis` was used, but thankfully, those fall only within kendo-jquery domain, so we can fix them.
=> Minor improvements

packages/default/scss/chip/_layout.scss, packages/fluent/scss/chip/_layout.scss, packages/nouvelle/scss/chip/_layout.scss
related to https://github.com/telerik/kendo-angular-private/issues/354
=> fix(pivotgrid): chip menu not properly positioned

packages/default/scss/dropzone/_layout.scss, packages/fluent/scss/dropzone/_layout.scss
`.k-dropzone-inner` is not clickable so the `cursor: pointer` style should be removed
=> Inner dropzone should not be clickable

packages/default/scss/pivotgrid/_layout.scss, packages/fluent/scss/pivotgrid/_layout.scss
fixes: https://github.com/telerik/kendo/issues/17251
=> fix(pivotgrid): fix vertical alignment of pivotgrid cells

packages/bootstrap/lib/swatches/bootstrap-3-dark.json, packages/bootstrap/lib/swatches/bootstrap-3.json, packages/bootstrap/lib/swatches/bootstrap-4-dark.json, packages/bootstrap/lib/swatches/bootstrap-4.json, packages/bootstrap/lib/swatches/bootstrap-main-dark.json, packages/bootstrap/lib/swatches/bootstrap-nordic.json, packages/bootstrap/lib/swatches/bootstrap-turquoise-dark.json, packages/bootstrap/lib/swatches/bootstrap-turquoise.json, packages/bootstrap/lib/swatches/bootstrap-urban.json, packages/bootstrap/lib/swatches/bootstrap-vintage.json
fixes: https://github.com/telerik/kendo-themes/issues/4314
=> fix: bootstrap swatches do not override inherited primary color

packages/default/scss/chip/_layout.scss, packages/fluent/scss/chip/_layout.scss, packages/nouvelle/scss/chip/_layout.scss
related to https://github.com/telerik/kendo-themes/pull/4290
The fix from the above PR breaks the Close icon alignment. It is no longer aligned in the middle.
The issue is not noticeable in the Default theme but it can be seen in the Bootstrap and the Material themes.
https://www.telerik.com/kendo-angular-ui-develop/components/buttons/chip/
=> fix(chip): close icon not properly aligned

packages/fluent/scss/core/color-system/_variables.scss
fixes https://github.com/telerik/kendo-themes/issues/4343
=> fix(fluent): add missing color class names

packages/default/scss/grid/_theme.scss
Closes: https://github.com/telerik/kendo-themes/issues/4309
=> fix(grid): increase sticky content selector specificity

.github/workflows/publish_npm_dev.yml
Lerna [canary releases](https://github.com/lerna/lerna/tree/main/libs/commands/publish#--canary) always bump minor version only. This is not ideal, especially for major versions where we have breaking changes.
To solve this, we can switch to [conventional-prerelease](https://github.com/lerna/lerna/tree/main/libs/commands/version#--conventional-prerelease), which will bump versions as follows:
```
- major: 1.0.0-dev.0 => 2.0.0-dev.0 
- minor: 1.0.0-dev.0 => 1.1.0-dev.0 
- patch: 1.0.0-dev.0 => 1.0.1-dev.0
``` 
/cc @radkostanev, @jivanova
=> ci(dev): switch to lerna conventional prerelease

packages/html/package.json, packages/html/src/dropdownlist/dropdownlist.spec.tsx, packages/html/src/grid/tests/grid-sticky-columns.tsx, packages/html/src/popover/popover.spec.tsx, packages/html/src/popover/tests/popover.tsx, packages/html/src/textbox/textbox.spec.tsx, packages/html/src/treeview/treeview.spec.tsx, tests/grid/grid-sticky-columns.html
Add `types` for the demos as part of the build.
Cleared up some typescript errors. One interesting one was the `prefix` property as it already exists on the native `span` elements, thus the need for `Omit<T, 'prefix'>`
=> Spec for demos

packages/html/package.json, packages/html/scripts/build.js
Tweak the distribution of the `html` package to enable more flexibility when consuming the package. Additionally, adding `d.ts` files to the dist through the `files` collection, as they do not seems to be published to npm, regardless of being generated after https://github.com/telerik/kendo-themes/pull/4453
=> chore(html): tweak distribution

packages/default/scss/icons/_layout.scss, packages/fluent/scss/icon/_layout.scss
The icon has a wrong size when svg is used with `k-icon-modifier`:
The icon should look like this:
=> fix(icon): wrong icon size when svg is used with k-icon-modifier

packages/default/scss/grid/_layout.scss, packages/fluent/scss/grid/_layout.scss
fixes https://github.com/telerik/kendo-themes/issues/4496
=> fix: make rows resizer to be visible for sticky columns

packages/default/scss/list/_layout.scss, packages/fluent/scss/list/_layout.scss
related to https://github.com/telerik/kendo-themes/pull/4541 and https://github.com/telerik/kendo-themes/issues/3388
=> fix(list): empty sticky header has a wrong height

packages/default/scss/treelist/_layout.scss, packages/fluent/scss/treelist/_layout.scss
part of: https://github.com/telerik/kendo-themes-private/issues/40
=> chore(treelist): use content box for toggle icon to prevent shrinking

packages/bootstrap/scss/_bootstrap-overrides.scss, packages/bootstrap/scss/_variables.scss, packages/bootstrap/scss/core/_index.scss
regression introduced in https://github.com/telerik/kendo-themes/pull/4518
This PR fixes variable's import order which results in incorrect bootstrap dark theme in v6.5.0.
=> fix(bootstrap); dark theme input colors

packages/default/scss/scrollview/_layout.scss, packages/fluent/scss/scrollview/_layout.scss
Related to https://github.com/telerik/kendo-themes-private/issues/141
During the effort in unifying the rendering of the ScrollView and after a discussion with @pepinho24  and @Juveniel it has become apparent that some suites ( jQuery and Angular ) are unable to reuse the animations provided through the themes.
We have addressed that issue by firstly scoping the animations to the `.k-scrollview-animate` class, however additional styling was needed in order to preserve the current behavior and this PR introduces that.
> NOTE: In cases where the animation is controlled by the component and specific styles for positioning are required e.g. Virtual ScrollView in jQuery or the implementation in Angular those will need to be set inline through the component
e.g. `position: absolute; top: 0; …
=> chore(scrollview): steamline scrollview-view styles

packages/fluent/scss/core/_index.scss
Regression of https://github.com/telerik/kendo-themes/pull/4518
Fixes the ability to configure the fluent them with the `use "" with ()` syntax
=> fix(fluent): forward variables in order to be configurable

packages/fluent/scss/dock-manager/_layout.scss
Fixes: https://github.com/telerik/kendo-themes/issues/4753
=> fix(dock-manager): fix toolbar buttons padding in fluent

.stylelintrc.json
addresses a fix in recent stylelint version: https://github.com/stylelint/stylelint/releases/tag/15.11.0
=> chore: stylelint allow longhand logical properties

packages/default/scss/dock-manager/_layout.scss, packages/fluent/scss/dock-manager/_layout.scss
Seems like the writing-mode issue with the button in Chrome has been resolved, so I am removing the workaround.
=> chore(dock-manager): remove no longer needed chrome specific styles

packages/default/scss/common/_indicators.scss, packages/fluent/scss/core/helpers/_indicators.scss, packages/html/src/gantt/tests/gantt.tsx, tests/gantt/gantt.html
The current time marker should not have a `width` property set because it is supposed to be used as both a horizontal and a vertical line.
The components (Scheduler and Gantt) should add the required property inline (either `width` or `height`), as they currently do.
=> fix(common): incorrectly set current time marker width

packages/html/src/timeline/timeline-card.spec.tsx, tests/timeline/timeline-horizontal.html, tests/timeline/timeline-vertical-alternating.html, tests/timeline/timeline-vertical.html
Cards in Timeline always have callouts, therefore we should enable this prop by default. When callout property is true, `k-card-with-callout` class is set to the card - https://github.com/telerik/kendo-themes/blob/develop/packages/html/src/card/card.spec.tsx#L69. Also, this recommendation was described in the [_Unify rendering for Timeline_ issue](https://github.com/telerik/kendo-themes-private/issues/193)
=> fix(html): enable callout property

packages/html/src/index.ts
Exports the helpers of (skeleton, rating, chat, pdf-viewer, orgchart, signature).
=> chore: export components helpers

packages/default/scss/gantt/_layout.scss, packages/fluent/scss/gantt/_layout.scss
Related to https://github.com/telerik/kendo-themes/pull/4839
With switching from `k-timeline` to `k-gantt-timeline` in the rendering and styles of the Gantt component we missed to consider that there might be styles related to `k-timeline` on which we may rely on.
Namely the styles for box-sizing [here](https://github.com/telerik/kendo-themes/blob/4a6a0cb7085a4b032405585e25da25fd4383d7d7/packages/default/scss/timeline/_layout.scss#L14), without which there is an issue with setting a specific row height - reported in jQuery.
=> fix(gantt): gantt-timeline children should have correct box-sizing

packages/bootstrap/docs/customization-input.md, packages/bootstrap/docs/customization.md, packages/bootstrap/scss/_bootstrap-overrides.scss, packages/bootstrap/scss/core/color-system/_swatch.scss
With the implementation of the color system in Bootstrap we were no longer relying on the styles from `_bootstrap-overrides` ( at least not in the same way as before )  -- these styles were never applied and the value of `input-bg` always defaulted to `#fff`, which causes issues in the Dark swatches.
=> Fix dark swatch input colors in Bootstrap

packages/default/scss/spreadsheet/_layout.scss
Closes: https://github.com/telerik/kendo-themes/issues/4886
=> fix(spreadsheet): file icon overlaps elements in export to pdf popup

packages/html/package.json, packages/html/scripts/build.js
In a node env we need either a type: module in package.json in order to load ESM modules from js files or CJS module with mjs files using ESM syntax. 
Without that some bundlers fail to load modules and build HTML specs in node env.
=> chore: add type module as default for bundlers

packages/fluent/scss/utils/_layout.scss, packages/utils/scss/_mixins.scss, packages/utils/scss/_variables.scss, packages/utils/scss/background/_background-color.scss, packages/utils/scss/border/_border-color.scss, packages/utils/scss/border/_outline-color.scss, packages/utils/scss/elevation/index.import.scss, packages/utils/scss/typography/_text-color.scss
related to https://github.com/telerik/kendo-themes-private/issues/220
With this PR, the color utility classes (background-color, border-color, text-color and outine-color) will be generated with CSS variables as follows:
```css
.k-bg-primary {
background-color: var(--kendo-color-primary, #ff6358);
}
.k-bg-inherit {
background-color: var(--kendo-color-inherit, inherit);
}
```
We do not generate utility classes for all `$kendo-colors`. We do it only for the main colors in order to keep the bundle with a reasonable size.
[These are the colors](https://github.com/telerik/kendo-themes/blob/color-utility-classes/packages/utils/scss/_variables.scss#L11) we generated utility classes for.
Before this change (with `$kendo-enable-color-system` set to `false`), the Default theme CSS file is **895 …
=> feat(utils): generate utility classes with css variables

packages/html/src/appbar/tests/appbar-rtl.tsx, packages/html/src/appbar/tests/appbar.tsx, tests/appbar/appbar-rtl.html, tests/appbar/appbar.html
In the [Appbar tests](https://github.com/telerik/kendo-themes/blob/d84d6dd15dc96b01d20ce0a202650d237e5c200c/tests/appbar/appbar.html) there is a `fillMode="solid"` property set, however the Appbar itself only has a `themeColor` property.
This PR removes the `fillMode` as it does not result to anything and causes confusion.
=> fix(html): appbar should not have fillMode

scripts/colors-migrator.sh
**NOTE: There might be scenarios that might cause unexpected/wrong results after executing the Colors Migrator script. The changes should be carefully reviewed before committing them.**
The Colors Migrator script checks all SCSS files in a given directory for "old" color variables and migrates them to the new Color System:
```bash
bash colors-migrator.sh source_directory --theme theme_name --functionality
```
The script has two functionalities (controlled with a flag) which MUST be executed in a specific order, otherwise the migration will not be successful and will lead to a broken codebase.
First, the script must be executed with the `--migrate_color_values` functionality/flag:
```bash
bash colors-migrator.sh app/styles --theme bootstrap --migrate_color_values
```
The above script …
=> chore: introduce colors migrator script

packages/utils/docs/customization.md, packages/utils/scss/spacing/_margin.scss, packages/utils/scss/spacing/_padding.scss
In this PR:
- Generate missing spacing-related utils;
- Remove examples with negative paddings, as values for padding cannot be negative;
=> chore: generate missing utils

packages/utils/scss/typography/_font-weight.scss
`k-font-*` utils were not using the correct css variables `--kendo-font-weight-*`, this PR addresses that
=> chore(utils): use correct css var in font weight utils

packages/utils/scss/flex-grid/_gap.scss
Same as padding / margin, gap should be related to the spacing system
=> chore: generate css variables for gap utils

packages/bootstrap/docs/customization-drawer.md, packages/bootstrap/docs/customization.md, packages/bootstrap/scss/drawer/_variables.scss, packages/classic/docs/customization-drawer.md, packages/classic/docs/customization.md, packages/classic/scss/drawer/_variables.scss, packages/default/docs/customization-drawer.md, packages/default/docs/customization.md, packages/default/scss/drawer/_layout.scss, packages/default/scss/drawer/_variables.scss, packages/fluent/docs/customization-drawer.md, packages/fluent/docs/customization.md, packages/fluent/scss/drawer/_layout.scss, packages/fluent/scss/drawer/_variables.scss, packages/material/docs/customization-drawer.md, packages/material/docs/customization.md, packages/material/scss/drawer/_variables.scss
This is based on feedback from `Ticket ID: 1648341` where they want to set the padding using SCSS variables.
Currently, it is only possible to do this using CSS:
```
.k-content-drawer {
padding-inline: 20px;
padding-block: 20px;
}
```
https://stackblitz.com/edit/react-siozrp-d1bfnw?file=app%2Fmain.jsx,app%2Fstyles.scss
=> Drawer use `$kendo-drawer-content-padding-x` and `$kendo-drawer-content-padding-y`

packages/default/scss/dataviz/_layout.scss, packages/fluent/scss/dataviz/_layout.scss
Sankey labels should not have hover effects and trigger mouse events.
cc/ @tsvetomir
=> Remove sankey label pointer-events

packages/default/scss/action-sheet/_layout.scss, packages/fluent/scss/action-sheet/_layout.scss
Reduce calc expression to workaround a build warning in create-react-app ( which is deprecated for ~2 years ).
Related: https://github.com/telerik/kendo-themes/issues/4337#issuecomment-1485379417
// cc @zdravkov, @elena-gancheva, @bptodorova
=> fix(action-sheet): reduce filter calc nesting

packages/bootstrap/docs/customization-common.md, packages/bootstrap/docs/customization-typography.md, packages/bootstrap/docs/customization.md, packages/bootstrap/scss/typography/_variables.scss, packages/classic/docs/customization-typography.md, packages/classic/docs/customization.md, packages/classic/scss/typography/_variables.scss, packages/default/docs/customization-common.md, packages/default/docs/customization-typography.md, packages/default/docs/customization.md, packages/default/scss/typography/_variables.scss, packages/material/docs/customization-typography.md, packages/material/docs/customization.md, packages/material/scss/typography/_variables.scss
these cause some issues in the katana docs
=> docs: remove unexpected whitespace in typography module

packages/core/docs/customization.md, packages/core/scss/color-system/_swatch.scss, packages/core/scss/functions/_color-system.import.scss, packages/core/scss/functions/index.import.scss
This adjustment is in big part related to the [Migration](https://www.telerik.com/design-system/docs/themes/theme-default/migration/) to the new Color System (ticket ID - 1652186).
If the user has made the following customization:
```scss
$kendo-color-primary: #9c27b0;
$kendo-panelbar-header-bg: $kendo-color-primary;
@import "@progress/kendo-theme-default/dist/all.scss";
```
They would need to migrate the above customization to the new Color System.
If they use the [Migration script](https://www.telerik.com/design-system/docs/themes/theme-default/migration/#automated-migration), they would get the following result, where the `k-color()` function will not work because it is not available/imported:
```scss
@import "@progress/kendo-theme-core/scss/functions/index.import.scss";
$kendo-colors: …
```
=> chore: move the k-color function in core/functions

packages/bootstrap/docs/customization-radii.md, packages/bootstrap/docs/customization.md, packages/bootstrap/scss/core/border-radii/index.import.scss, packages/fluent/docs/customization-radii.md, packages/fluent/docs/customization.md, packages/fluent/scss/core/border-radii/_index.scss, packages/material/docs/customization-radii.md, packages/material/docs/customization.md, packages/material/scss/core/border-radii/index.import.scss
According to [this issue](https://github.com/telerik/web-components-ux/issues/943#issuecomment-1845388821), there should be values for full border radius in the Material and Fluent themes as well
=> Material fluent border radius

.github/workflows/publish_nuget.yml
Since ubuntu-latest is now ubuntu-24.04 and does not have support for NuGet.
We are switching to ubuntu-22.04 until NuGet is available.
=> Rollback to ubuntu-22.04 due to lack of NuGet in latest

packages/bootstrap/scss/typography/_index.scss, packages/classic/scss/typography/_index.scss, packages/default/scss/typography/_index.scss, packages/fluent/scss/typography/_index.scss, packages/material/scss/typography/_index.scss
As pointed in [this issue](https://github.com/telerik/kendo-themes-private/issues/245), the Typography component should suggest only font-related properties, but not space related
=> Remove margin utils

packages/bootstrap/docs/customization-scheduler.md, packages/bootstrap/docs/customization.md, packages/bootstrap/scss/scheduler/_variables.scss, packages/classic/docs/customization-scheduler.md, packages/classic/docs/customization.md, packages/classic/scss/scheduler/_variables.scss, packages/default/docs/customization-scheduler.md, packages/default/docs/customization.md, packages/default/scss/scheduler/_variables.scss, packages/material/docs/customization-scheduler.md, packages/material/docs/customization.md, packages/material/scss/scheduler/_variables.scss
Fixes a bug introduced with https://github.com/telerik/kendo-themes/pull/5165 where recurring Scheduler events have wrong margin in rtl mode.
=> fix(scheduler): recurring events have incorrect margin in rtl

packages/default/scss/input/_layout.scss, packages/fluent/scss/input/_layout.scss, packages/nouvelle/scss/input/_layout.scss
Fixes https://github.com/telerik/kendo-themes/issues/5242
Another option may be to avoid flexbox for the `select` element, but this may need more lines of code.
=> fix(pager): select value in adaptive pager has wrong vertical alignment in Safari

packages/html/src/action-sheet/action-sheet.spec.tsx
Resolves type errors in the action sheet spec related to this [dependency bump](https://github.com/telerik/kendo-themes/pull/5248)
=> chore(html): resolve action-sheet eslint type errors

packages/default/scss/pdf-viewer/_layout.scss, packages/fluent/scss/pdf-viewer/_layout.scss
Fixes: https://github.com/telerik/kendo-themes/issues/5256
Notes:
As discussed with @Stamo-Gochev, both _**k-link-annotation**_ and _**k-highlight-editor-disabled**_ would be added to the component (currently they don't present)
=> fix(pdf-viewer): link annotations are not clickable

.github/workflows/_create-screenshots.yml, .github/workflows/_render-test-pages.yml, packages/core/docs/customization.md, packages/core/scss/functions/_color.import.scss
closes: [#5296](https://github.com/telerik/kendo-themes/issues/5296)
=> fix(core): color.channel functions should be backwards compatible

package-lock.json, packages/html/package.json, scripts/render-test-pages.mjs
With React 19, `<script>` tags inside components are now rendered instead of being ignored.
It seems like it will do this only if the tag is a direct child of `<body>`
What I've tried so far is:
- remove the `<script>` tag from `packages/html/shared/index.html` and add it later in `build-tests.js`
> This does not seem like a valid solution since it seems it does not matter whether the `<script>` is in `packages/html/shared/index.html` or `packages/html/dist/`. It will be rendered if it is a direct child of body.
- wrap the `<script>` tag inside a `div`
> While it may not seem like the best solution it does work and does not produce an additional `<div>` wrapper in our tests.
- trim the extra <script> tag before creating screenshots
> This seems like a more valid solution
=> chore(html): prevent react 19 script tag duplication

packages/core/scss/components/dataviz/_layout.scss, packages/fluent/scss/dataviz/_layout.scss
closes https://github.com/telerik/kendo-themes/issues/5491
=> fix(charts): add display properties to diagram and gauge

.github/workflows/_compile-themes.yml, .github/workflows/_docs-check.yml, .github/workflows/ci.yml, build/mark-checks.sh, nx.json, package.json, packages/bootstrap/package.json, packages/classic/package.json, packages/core/package.json, packages/default/package.json, packages/fluent/package.json, packages/material/package.json, packages/utils/package.json
This PR augments the CI to attach granular commit statuses to any auto-generated visual snapshot commit.
* `detect-changes` now exposes snapshot_sha when visual test files are added or modified and pushed.
* New `set-commit-status` job:
* Runs only if a snapshot commit exists: if: ${{ always() && needs.detect-changes.outputs.snapshot_sha }}.
* Depends on all status-producing jobs to collect their results.
* Uses actions/github-script to post commit statuses (Unit, Integration, Lint scripts, Lint styles, A11y, Docs, Visual) to the snapshot commit.
* Visual context marked success when snapshot update succeeds; skipped/cancelled upstream jobs map to failure per current mapping.
Visual snapshot commits now carry the full matrix of CI statuses, enabling reviewers to gate or trust regenerated …
=> chore: add docs to ci

packages/bootstrap/package.json, packages/classic/package.json, packages/core/package.json, packages/default/package.json, packages/fluent/package.json, packages/material/package.json, packages/utils/package.json
`npm run docs:check` failed on Windows with error: `.' was unexpected at this time.`
The scripts used Unix shell syntax incompatible with Windows `cmd.exe`:
```json
"docs:check": "npm run docs && git diff --name-only --exit-code -- docs || (echo 'Docs out of date (theme).' && exit 1)"
```
Simplified to cross-platform compatible syntax:
```json
"docs:check": "npm run docs && git diff --name-only --exit-code -- docs"
```
The `git diff --exit-code` command naturally returns a non-zero exit code when docs are out of date, eliminating the need for shell-specific error handling.
=> chore: make docs:check cross-platform

packages/core/scss/components/slider/_layout.scss
closes: https://github.com/telerik/kendo-themes/issues/5354
The styles for the slider tooltip callout come from the Tooltip component, and the ones coming from the slider are redundant (and in fact compile to invalid CSS)
=> chore(slider): remove reduntant styles

.github/workflows/_package-report.yml, packages/html/package.json
closes: https://github.com/telerik/kendo-themes-private/issues/396
Enhanced the Package Report workflow to include the HTML package alongside other Kendo UI themes:
- **Added HTML package to matrix**: Included `html` in both `extract-pr-data` and `extract-develop-data` job matrices
- **Different build command**: HTML package uses `npm run build` instead of `npm run sass:compile:all` 
- **Size measurement in MB**: HTML package size is calculated and displayed in MB (instead of KB) since it's significantly larger (~84MB vs ~100KB for CSS themes)
- **Updated report table**: Added HTML column to the comparison table with appropriate MB units
- HTML package measures total `dist/` directory size (includes cjs & esm directory)
- Compressed size uses tar.gz of entire dist directory for accurate …
=> Add HTML to Packages Report Tests

packages/core/scss/components/window/_layout.scss
Related to https://github.com/telerik/kendo-ui-core/issues/8361
When using cardinal directions, no logical properties should be used
=> fix(window): not resizing properly from sides in RTL

.github/workflows/_package-report.yml
Fixed package reporter compile time indicators not displaying properly due to incorrect dependency caching. The workflow was using the same (newer) dependencies for both PR and develop measurements, causing identical results and hiding performance regressions. 
Updated the develop measurement job to checkout the develop branch before dependency installation, ensuring proper isolation between PR and baseline measurements. This enables accurate tracking of compile time differences, particularly important for detecting performance impacts from dependency updates like the Sass version bump.
Also reduced the compile time tolerance from `2 seconds` to `1 second` for more sensitive performance change detection.
Real case example: https://github.com/telerik/kendo-themes/pull/5587
=> chore(ci): adjust reporter cacheing

.github/workflows/_package-report.yml
Reverts the tolerance to 2 seconds from https://github.com/telerik/kendo-themes/pull/5609.
As 1 second proved to be flaky.
=> chore(ci): revert reporter tolerance

.github/workflows/_package-report.yml
1. **Median of 5 runs** - Uses middle value instead of average to ignore CI runner outliers
Example: `[5.2, 5.4, 5.3, 5.5, 9.1]` → median = `5.4s` (ignores 9.1s outlier)
2. **Decimal precision** - Changed from integer seconds to `date +%s.%N` for nanosecond accuracy (displays as `5.4 s` instead of `5 s`)
3. **Hybrid tolerance** - Hides indicators only when BOTH absolute (<1s) AND relative (<15%) changes are small, catches real regressions while filtering CI variance
More reliable compile time comparisons that filter CI noise while catching performance changes ≥15%.
=> chore(ci): fine tune package reporter
